id: htaccess-config

info:
  name: HTaccess config file
  author: Yash Anand @yashanand155
  severity: info
  metadata:
    max-request: 6
  tags: miscellaneous,misc,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/.htaccess"
      - "{{BaseURL}}/example.htaccess"
      - "{{BaseURL}}/_.htaccess"
      - "{{BaseURL}}/sample.htaccess"
      - "{{BaseURL}}/a.htaccess"
      - "{{BaseURL}}/htaccess_for_page_not_found_redirects.htaccess"

    stop-at-first-match: true
    matchers:
      - type: word
        words:
          - RewriteRule
          - </IfModule>
          - <IfModule
        condition: and
# digest: 4a0a00473045022100d1d5022ec4c8518adfa48e72fb8522566c475c217bb1e1e251e068d4027789b002206b53f229477eb41c2716b72bcedf72380ae54caaf919f0c2e03722693d41f1b8:922c64590222798bb761d5b6d8e72950