id: kubernetes-pods-api

info:
  name: Kubernetes Pods - API Discovery & Remote Code Execution
  author: ilovebinbash,geeknik,0xtavian
  severity: critical
  description: A Kubernetes Pods API was discovered. When the service port is available, unauthenticated users can execute commands inside the container.
  reference:
    - https://github.com/officialhocc/Kubernetes-Kubelet-RCE
    - https://blog.binaryedge.io/2018/12/06/kubernetes-being-hijacked-worldwide/
  metadata:
    max-request: 2
  tags: k8,unauth,kubernetes,devops,misconfig

http:
  - method: GET
    path:
      - '{{BaseURL}}/pods'
      - '{{BaseURL}}/api/v1/pods'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "apiVersion"

      - type: word
        words:
          - "application/json"
        part: header

      - type: status
        status:
          - 200
# digest: 4a0a0047304502206c60f6ba4b2e2609165b5501903ba68f525a2f92f280f5cb72367ba429a0bb96022100c6b119e1faa27294068554b498e76cf7d617a1d47c616d1ceda2d7f7f51364a0:922c64590222798bb761d5b6d8e72950