id: kubernetes-metrics

info:
  name: Detect Kubernetes Exposed Metrics
  author: pussycat0x
  severity: low
  description: Information Disclosure of Garbage Collection
  reference:
    - https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metrics-in-kubernetes
  metadata:
    max-request: 1
  tags: kubernetes,exposure,devops,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        condition: and
        words:
          - "namespace"
          - "HELP"
          - "TYPE"
          - "kube"

      - type: status
        status:
          - 200
# digest: 4a0a004730450220732bac8ba520ddb73283b26c2a71f4d2a5bfc4618e927216b8a2724093a3e0d902210082242fdc701f7bdebd62d851c8862ba9078eb5b4bf36a0d207836a83fcbdf473:922c64590222798bb761d5b6d8e72950