id: kube-state-metrics

info:
  name: Kube State Metrics Exposure
  author: ja1sh
  severity: low
  description: |
    An attacker can detect the public instance of a Kube-State-Metrics metrics. The Kubernetes API server exposes data about the count, health, and availability of pods, nodes, and other Kubernetes objects.
  classification:
    cpe: cpe:2.3:a:kubernetes:kube-state-metrics:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: kubernetes
    product: kube-state-metrics
    shodan-query: title:Kube-state-metrics
  tags: misconfig,exposure,kube-state-metrics,k8s,kubernetes

http:
  - method: GET
    path:
      - "{{BaseURL}}/metrics"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - kube-state-metrics
          - go_goroutines
        condition: and

      - type: status
        status:
          - 200
# digest: 490a0046304402201f35972cb8ae12ecb2a017de72bd60890d936047d6500bf8b6a30b19deca6e7e022019244e7540126097df03ea1668cf56595ff6efa45d69f04d992950f5bb0a08c6:922c64590222798bb761d5b6d8e72950