id: unauth-etcd-server

info:
  name: Etcd Server - Unauthenticated Access
  author: sharath,pussycat0x
  severity: high
  description: |
    A Kubernetes etcd server stores the cluster secrets and configurations files. Anonymous access on etcd allows unauthenticated access the data without providing any authentication credentials.
  remediation: https://etcd.io/docs/v2.3/authentication
  reference:
    - https://www.optiv.com/insights/source-zero/blog/kubernetes-attack-surface
  metadata:
    verified: true
    max-request: 1
    shodan-query: product:"etcd"
  tags: tech,k8s,kubernetes,devops,etcd,unauth,anonymous,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/v2/keys/"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"node":'
          - '"key":'
        condition: and

      - type: word
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100fa8f301711db545583d8709b5ea2c24f51d79a2fc94c88a9eeaec2940cb7f6fe022100f8e2c2b6079124bce64987c9097f88016ce446562136f6db3300ccd660503a64:922c64590222798bb761d5b6d8e72950