id: dockerhub-pat

info:
  name: Docker Hub Personal Access Token
  author: DhiyaneshDK
  severity: info
  reference:
    - https://github.com/praetorian-inc/noseyparker/blob/main/crates/noseyparker/data/default/builtin/rules/dockerhub.yml
    - https://docs.docker.com/security/for-developers/access-tokens/
  metadata:
    verified: true
  tags: docker,keys,file

file:
  - extensions:
      - all

    extractors:
      - type: regex
        part: body
        regex:
          - \b(dckr_pat_[a-zA-Z0-9_-]{27})(?:$|[^a-zA-Z0-9_-])
# digest: 490a00463044022027c1ddcc2eb5d7c0310984b2217278518787d09ace4aa84d7ab14d1e339a3aea02203c4a531c474465b904dd9f316e4872d6fb27316fabb88995a531168118e497fd:922c64590222798bb761d5b6d8e72950