id: phpmyadmin-misconfiguration

info:
  name: phpmyadmin Data Exposure
  author: pussycat0x
  severity: medium
  description: An unauthenticated instance of phpmyadmin was discovered, which could be leveraged to access sensitive information.
  reference:
    - https://www.exploit-db.com/ghdb/6997
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 2
    vendor: phpmyadmin
    product: phpmyadmin
    shodan-query:
      - "http.title:phpMyAdmin"
      - http.title:"phpmyadmin"
      - http.component:"phpmyadmin"
      - cpe:"cpe:2.3:a:phpmyadmin:phpmyadmin"
    fofa-query:
      - body="pma_servername" && body="4.8.4"
      - title="phpmyadmin"
  tags: phpmyadmin,misconfig,edb

flow: http(1) || http(2)

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpmyadmin/index.php?db=information_schema"

    matchers-condition: and
    matchers:
      - type: status
        internal: true
        status:
          - 200

      - type: word
        internal: true
        part: body
        words:
          - "var db    = 'information_schema';"
          - "var opendb_url = 'db_structure.php';"
        condition: and

      - type: word
        internal: true  
        part: body
        words:
          - 'name="login_form"'
          - 'id="input_username"'
        negative: true
        condition: or

  - method: GET
    path:
      - "{{BaseURL}}/phpMyAdmin/index.php?db=information_schema"

    matchers-condition: and
    matchers:
      - type: status
        internal: true
        status:
          - 200

      - type: word
        part: body
        internal: true
        condition: and
        words:
          - "db:\"information_schema\""
          - "opendb_url:\"db_structure.php\""

      - type: word
        internal: true
        part: body
        words:
          - 'name="login_form"'
          - 'id="input_username"'
        negative: true
        condition: or
