id: accueil-wampserver

info:
  name: Accueil WAMPSERVER Configuration Page - Detect
  author: tess
  severity: low
  description: Accueil WAMPSERVER configuration page was detected.
  metadata:
    verified: true
    shodan-query: http.title:"Accueil WAMPSERVER"
  tags: exposure,accueil,wampserver,config

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Accueil WAMPSERVER"
          - "Configuration Serveur"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/08
