id: apache-config

info:
  name: Apache Configuration File - Detect
  author: sheikhrishad
  severity: medium
  description: Apache configuration file was detected.
  reference:
    - https://httpd.apache.org/docs/2.4/configuring.html
  tags: config,exposure,apache

requests:
  - method: GET
    path:
      - "{{BaseURL}}/apache.conf"

    matchers:
      - type: dsl
        dsl:
          - "contains(body, '<Directory') && contains(body, '</Directory>') && status_code == 200"
          - "contains(body, '<VirtualHost') && contains(body, '</VirtualHost>') && status_code == 200"
        condition: or

# Enhanced by cs on 2023/02/13
