id: circleci-config

info:
  name: CircleCI Configuration File - Detect
  author: geeknik
  severity: low
  description: CircleCI config.yml file was detected.
  reference:
    - https://circleci.com/docs/2.0/sample-config/
  tags: config,exposure,circleci

requests:
  - method: GET
    host-redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/.circleci/config.yml"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'regex("^version: ", body) && contains(body, "jobs:")'

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/08
