id: circleci-ssh-config

info:
  name: CircleCI SSH Configuration - Detect
  author: geeknik
  severity: low
  description: CircleCI ssh-config file was detected.
  tags: config,exposure,circleci

requests:
  - method: GET
    host-redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/.circleci/ssh-config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Host"
          - "HostName"
          - "IdentityFile"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/08
