id: cisco-network-config

info:
  name: Cisco System Network Configuration Page - Detect
  author: DhiyaneshDk
  severity: low
  description: Cisco System Network configuration page was detected. Page lists whole network configuration and internal logs of Cisco IP phones.
  reference:
    - https://www.exploit-db.com/ghdb/5430
  tags: exposure,cisco,edb,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/CGI/Java/Serviceability?adapter=device.statistics.configuration"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Network Configuration"
        part: body

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/08
