id: codeception-config

info:
  name: Codeception YAML Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Codeception YAML configuration file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"codeception.yml"
  tags: exposure,devops,codeception,config,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/codeception.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "paths:"
          - "settings:"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
