id: debug-vars

info:
  name: Golang Expvar - Detect
  author: luqman
  severity: info
  description: Golang expvar function exposes multiple public variables via HTTP such as stack trace information and server operation counters.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: go,debug,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/debug/vars"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"memstats":'
          - '"cmdline":'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
