id: editor-exposure

info:
  name: Editor Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Editor configuration file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"editorconfig"
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.editorconfig"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "= true"
          - "= space"
        condition: or

      - type: word
        part: header
        words:
          - "application/json"
          - "text/html"
        negative: true
        condition: or

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/02/13
