id: exposed-darcs

info:
  name: Darcs Configuration - Detect
  author: daffainfo
  severity: low
  description: Darcs configuration was detected.
  reference:
    - http://darcs.net/Using/Configuration#sources
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_darcs/prefs/binaries"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Binary file regexps"

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
