id: exposed-ds_store

info:
  name: Exposed DS_Store File
  author: pwnhxl
  severity: medium
  reference:
    - https://github.com/lijiejie/ds_store_exp
  tags: exposure,ds_store,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.DS_Store"

    matchers-condition: and
    matchers:
      - type: binary
        binary:
          - "0000000142756431"

      - type: status
        status:
          - 200
