id: exposed-bzr

info:
  name: Bazaar Configuration - Detect
  author: daffainfo
  severity: low
  description: Bazaar configuration was detected.
  reference:
    - http://doc.bazaar.canonical.com/beta/en/user-reference/configuration-help.html
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.bzr/branch/branch.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "parent_location"
          - "push_location"
        condition: or

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/plain"

# Enhanced by md on 2023/02/09
