id: exposed-hg

info:
  name: HG Configuration - Detect
  author: daffainfo
  severity: low
  description: HG configuration was detected.
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.hg/hgrc"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[paths]"
          - "default"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
