id: exposed-authentication-asmx

info:
  name: Authentication.asmx - Detect
  author: DhiyaneshDk
  severity: low
  description: Authentication Web Service authentication.asmx file was detected.
  reference:
    - https://www.exploit-db.com/ghdb/6604
  tags: config,exposure,edb

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_vti_bin/Authentication.asmx?op=Mode"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Authentication Web Service"
        part: body

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
