id: firebase-config-exposure

info:
  name: Firebase Configuration - Detect
  author: geeknik
  severity: low
  description: Firebase configuration was detected.
  reference:
    - https://github.com/firebase/firebaseui-web/blob/master/demo/public/sample-config.js
  tags: firebase,exposure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/public/config.js"
      - "{{BaseURL}}/config.js"

    matchers-condition: and
    matchers:

      - type: word
        words:
          - "apiKey:"
          - "authDomain:"
          - "databaseURL:"
          - "storageBucket:"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
