id: ftp-credentials-exposure

info:
  name: FTP Credentials Exposure
  author: pikpikcu
  severity: high
  description: FTP credentials were detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  tags: config,ftp,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ftpsync.settings"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - FTPSync
          - overwrite_newer_prevention
          - default_folder_permissions
        part: body
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/09
