id: nagios-status-page

info:
  name: Nagios Current Status Page - Detect
  author: dhiyaneshDk
  severity: low
  description: Nagios current status page was detected.
  reference:
    - https://www.exploit-db.com/ghdb/6918
  tags: exposure,nagios,status,edb

requests:
  - method: GET
    path:
      - '{{BaseURL}}/nagios/cgi-bin/status.cgi'
      - '{{BaseURL}}/cgi-bin/nagios4/status.cgi'
      - '{{BaseURL}}/cgi-bin/nagios3/status.cgi'

    matchers:
      - type: word
        words:
          - Current Network Status

# Enhanced by md on 2023/02/22
