id: opcache-status-exposure

info:
  name: OPcache Status Page - Detect
  author: pdteam
  severity: low
  description: OPcache status page was detected.
  tags: config,exposure,status

requests:
  - method: GET
    path:
      - "{{BaseURL}}/opcache-status/"
      - "{{BaseURL}}/php-opcache-status/"
      - "{{BaseURL}}/opcache-status/opcache.php"
    matchers:
      - type: word
        words:
          - "<th>opcache_enabled</th>"
          - "<th>opcache_hit_rate</th>"
        condition: and
        part: body

# Enhanced by md on 2023/02/22
