id: perl-status

info:
  name: Apache Mod_perl Status Page - Detect
  author: pdteam
  severity: info
  description: Apache mod_perl status page was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  reference: https://perl.apache.org/
  tags: config,exposure,apache,status

requests:
  - method: GET
    path:
      - '{{BaseURL}}/perl-status'
    matchers:
      - type: word
        words:
          - "<title>Apache2::Status"
          - "Perl version"
        condition: and

# Enhanced by md on 2023/02/22
