id: php-fpm-config

info:
  name: PHP-FPM Configuration Page - Detect
  author: sheikhrishad
  severity: low
  description: PHP-FPM configuration page was detected.
  tags: config,exposure,php

requests:
  - method: GET
    path:
      - "{{BaseURL}}/php-fpm.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "FPM Configuration"
          - "Pool Definitions"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/22
