id: phpstan-config

info:
  name: PHPStan Configuration Page - Detect
  author: DhiyaneshDK
  severity: low
  description: PHPStan configuration page was detected.
  metadata:
    verified: true
    shodan-query: html:"phpstan.neon"
  tags: devops,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/phpstan.neon"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'parameters:'

      - type: word
        part: header
        words:
          - "text/html"
          - "application/javascript"
        negative: true

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/22
