id: pre-commit-config

info:
  name: Pre-commit Configuration File - Detect
  author: DhiyaneshDk
  severity: low
  description: Pre-commit configuration file was detected.
  metadata:
    verified: true
  tags: exposure,devops,config,cicd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.pre-commit-config.yaml"
      - "{{BaseURL}}/pre-commit-config.yaml"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "repos:"
          - "hooks:"
          - "rev:"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/22
