id: proftpd-config

info:
  name: ProFTPD Configuration File - Detect
  author: sheikhrishad
  severity: low
  description: ProFTPD configuration file was detected.
  tags: config,exposure,proftpd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/proftpd.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ProFTPD"
          - "ServerName"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
