id: proxy-wpad-exposure

info:
  name: Web Proxy Auto-Discovery Configuration File - Detect
  author: DhiyaneshDk
  severity: low
  description: Web Proxy Auto-Discovery configuration file was detected.
  metadata:
    verified: true
    shodan-query: html:"wpad.dat"
  tags: config,exposure,proxy

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wpad.dat"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "FindProxyForURL"
          - "url"
          - "host"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
