id: rails-database-config

info:
  name: Ruby on Rails Database Configuration File - Detect
  author: pdteam,geeknik
  severity: low
  description: Ruby on Rails database configuration file was detected.
  tags: config,exposure,rails

requests:
  - method: GET
    path:
      - "{{BaseURL}}/config/database.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "adapter:"
          - "database:"
          - "production:"
        condition: and
        part: body

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
