id: robomongo-credential

info:
  name: MongoDB Credentials - Detect
  author: geeknik
  severity: high
  description: MongoDB credentials file used by RoboMongo was detected.
  tags: mongodb,robomongo,disclosure,config

requests:
  - method: GET
    path:
      - "{{BaseURL}}/db/robomongo.json"
      - "{{BaseURL}}/robomongo.json"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "application/json"

      - type: word
        words:
          - "databaseName"
          - "userName"
          - "userPassword"
          - "serverHost"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
