id: ruijie-information-disclosure

info:
  name: Ruijie Login Panel - Detect
  author: pikpikcu
  severity: high
  description: Ruijie login panel was detected.
  reference:
    - https://www.cnblogs.com/cHr1s/p/14499858.html
  tags: ruijie,config,exposure

requests:
  - method: GET
    path:
      - '{{BaseURL}}/login.php'

    matchers-condition: and
    matchers:

      - type: regex
        regex:
          - '"role":"super_admin","name":"(.*)","password":"(.*)"'
        part: body
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
