id: saia-web-server

info:
  name: Saia PCD Web-Server Configuration Page - Detect
  author: DhiyaneshDk
  severity: low
  description: Saia PCD Web-Server configuration page was detected.
  reference:
    - https://www.exploit-db.com/ghdb/6865
  tags: edb,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/loadtextfile.htm#programinfo"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>Saia PCD Web Server</title>"
        part: body

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
