id: sftp-config-exposure

info:
  name: SFTP Configuration File - Detect
  author: geeknik
  severity: high
  description: SFTP configuration file was detected.
  reference:
    - https://blog.sucuri.net/2012/11/psa-sftpftp-password-exposure-via-sftp-config-json.html
    - https://www.acunetix.com/vulnerabilities/web/sftp-ftp-credentials-exposure/
    - https://codexns.io/products/sftp_for_sublime/settings
  metadata:
    verified: true
    github-query: filename:sftp-config.json
  tags: sftp,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/sftp-config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"host":'
          - '"user":'
          - '"password":'
          - '"remote_path":'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
