id: ssh-authorized-keys

info:
  name: SSH Authorized Keys File - Detect
  author: geeknik
  severity: low
  description: SSH authorized keys file was detected.
  reference:
    - https://www.ssh.com/academy/ssh/authorized-key
  tags: config,exposure,ssh

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.ssh/authorized_keys"
      - "{{BaseURL}}/_/.ssh/authorized_keys"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ssh-dss"
          - "ssh-ed25519"
          - "ssh-rsa"
          - "ecdsa-sha2-nistp256"
        condition: or

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
