id: svnserve-config

info:
  name: Svnserve Configuration File - Detect
  author: sheikhrishad
  severity: low
  description: Svnserve configuration file was detected.
  tags: config,exposure,svnserve

requests:
  - method: GET
    path:
      - "{{BaseURL}}/svnserve.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "This file controls the configuration of the svnserve daemon"

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
