id: symfony-profiler

info:
  name: Symfony Profiler - Detect
  author: pdteam
  severity: high
  description: Symfony profiler was detected.
  metadata:
    verified: true
    shodan-query: http.html:"symfony Profiler"
  tags: config,exposure,symfony

requests:
  - method: GET
    path:
      - "{{BaseURL}}/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/app_dev.php/_profiler/empty/search/results?limit=10"

    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - "Symfony Profiler"

# Enhanced by md on 2023/02/23
