id: tox-ini

info:
  name: Tox Configuration File - Detect
  author: geeknik
  severity: low
  description: Tox configuration file was detected.
  reference: https://tox.wiki/en/latest/config.html
  metadata:
    verified: true
    shodan-query: html:"tox.ini"
  tags: exposure,config,tox

requests:
  - method: GET
    path:
      - "{{BaseURL}}/tox.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "[tox]"
          - "[testenv]"
        condition: and

      - type: word
        part: header
        words:
          - "application/octet-stream"

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/24
