id: websheets-config

info:
  name: Websheets Configuration File - Detect
  author: geeknik
  severity: low
  description: Websheets configuration file was detected.
  reference:
    - https://github.com/daveagp/websheets
  metadata:
    verified: true
  tags: websheets,config,exposure,files

requests:
  - method: GET
    path:
      - '{{BaseURL}}/ws-config.json'
      - '{{BaseURL}}/ws-config.example.json'

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"db-password":'
          - '"db-database":'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/24
