id: xprober-service

info:
  name: X Prober Server - Information Disclosure
  author: pdteam
  severity: low
  description: X Prober Server information disclosure was detected.
  reference:
    - https://twitter.com/bugbounty_tips/status/1339984643517423616
  tags: config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/xprober.php"
    matchers:
      - type: word
        words:
          - '"appName":"X Prober"'
          - '<title>X Prober'
        condition: and

# Enhanced by md on 2023/02/24
