id: ecology-mysql-config

info:
  name: Fanwei OA E-Office - Information Disclosure
  author: ritikchaddha
  severity: medium
  description: |
    Fanwei E-Office mysql_config.ini file can be directly accessed, leaking database account password and other information.
  metadata:
    verified: true
    max-request: 1
    fofa-query: app="泛微-EOffice"
  tags: fanwei,ecology,exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/mysql_config.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "dataurl"
          - "datapassword"
          - "datauser"
        condition: and

      - type: word
        part: header
        words:
          - text/plain

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100dbb1b0c53302b0bb841738bf6eef8fcd31680267592574d4ff061aa5b050c4b0022100bf834aefde7db904c91f4bd7de0c7f32ff0038363dc924560928def6f7ca8829:922c64590222798bb761d5b6d8e72950