id: front-page-misconfig

info:
  name: FrontPage configuration information discloure
  author: JTeles,pikpikcu
  severity: info
  reference:
    - https://docs.microsoft.com/en-us/archive/blogs/fabdulwahab/security-protecting-sharepoint-server-applications
  metadata:
    max-request: 2
  tags: misconfig,exposure,frontpage

http:
  - method: GET
    path:
      - "{{BaseURL}}/_vti_inf.html"
      - "{{BaseURL}}/_vti_pvt/service.cnf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "vti_extenderversion:"
          - "FPVersion="
        part: body

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100a9ac9726aa943f4e090dbac6d2b794fe291b8af4f92357dedca606cf5ef0ac44022100a4536ae57383d5fc2f34ff4c72c3ec27c39fa099cf8a80b4208ed8f70d889611:922c64590222798bb761d5b6d8e72950