id: tcpconfig

info:
  name: Rockwell Automation TCP/IP Configuration Information - Detect
  author: dhiyaneshDK
  severity: medium
  description: TCP/IP configuration information was detected.
  reference:
    - https://www.rockwellautomation.com/
    - https://www.exploit-db.com/ghdb/6782
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,edb,logs,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/tcpconfig.html"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "TCP/IP Configuration"

      - type: status
        status:
          - 200
# digest: 4a0a0047304502200a94fe81ac2d2ce06ee2d38bdae9d7c391b410888ae491fd795ae34e0bb68417022100dbb7ff486ef83278e54694b17c3327803b0925824745a30f3f92df3c6e3850a1:922c64590222798bb761d5b6d8e72950