id: thanos-prometheus-exposure

info:
  name: Thanos Prometheus Setup - Exposure
  author: DhiyaneshDk,righettod
  severity: high
  description: |
    Thanos graph endpoint was detected.
  reference:
    - https://thanos.io/
    - https://github.com/thanos-io/thanos
  metadata:
    verified: true
    max-request: 2
    shodan-query: title:"Thanos | Highly available Prometheus setup"
    fofa-query: icon_hash="29632872"
  tags: thanos,prometheus,exposure,setup,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/graph"
      - "{{BaseURL}}/classic/graph"

    stop-at-first-match: true
    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_all(body, "THANOS_COMPONENT", "THANOS_QUERY_URL") || contains_all(body, "<title>Thanos", "href=\"/classic/\">Thanos</a>")'
        condition: and
# digest: 490a0046304402203edd5a1ba5a48cf6b076d803975cf0ffb0f35df443b940007f6e5f79dfa1ded802204971712b2f6d0aaf277a6af474812dbf9094d4e46f03128c43e9a600106f8774:922c64590222798bb761d5b6d8e72950