id: thanos-prometheus-exposure

info:
  name: Thanos Prometheus Setup - Exposure
  author: DhiyaneshDk
  severity: high
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Thanos | Highly available Prometheus setup"
    fofa-query: icon_hash="29632872"
  tags: thanos,prometheus,exposure,setup

http:
  - method: GET
    path:
      - "{{BaseURL}}/graph"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "THANOS_COMPONENT"
          - "THANOS_QUERY_URL"
        condition: and

        part: body
      - type: status
        status:
          - 200
