id: wamp-server-configuration

info:
  name: default-wamp-server-page
  author: pussycat0x
  severity: medium
  description: Wamp default page will expose sensitive configuration and vhosts.
  reference: https://www.exploit-db.com/ghdb/6891.
  metadata:
    max-request: 1
  tags: wamp,exposure,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'contains(tolower(body), "wampserver")'

      - type: status
        status:
          - 200
# digest: 4a0a0047304502205e4870a00269497566e62788aca197bd8cb537dc69c4fecc4c8be6f39524363c022100dc7adbb448f8375b736017bfe5be002c950a0423e9c26b0a87682620c4932258:922c64590222798bb761d5b6d8e72950