id: lidarr-settings-indexers

info:
  name: Lidarr Settings Indexers Exposure
  author: ProjectDiscoveryAI
  severity: medium
  description: |
    This template checks for exposed Lidarr indexer settings which can lead to sensitive information disclosure.

http:
  - raw:
      - |
        GET /lidarr/settings/indexers HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Lidarr"
          - "Indexer"
          - "Settings"