id: prowlarr-general-settings

info:
  name: Prowlarr General Settings Exposure
  author: ProjectDiscoveryAI
  severity: medium
  description: |
    This template checks for exposed Prowlarr general settings which can lead to sensitive information disclosure.

http:
  - raw:
      - |
        GET /prowlarr/settings/general HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Prowlarr"
          - "Settings"
          - "General"