id: readarr-settings-indexers

info:
  name: Readarr Settings Indexers Exposure
  author: ProjectDiscoveryAI
  severity: medium
  description: |
    This template checks for exposed Readarr indexer settings which can lead to sensitive information disclosure.

http:
  - raw:
      - |
        GET /readarr/settings/indexers HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Readarr"
          - "Indexer"
          - "Settings"