id: sonarr-indexer-settings-exposure

info:
  name: Sonarr Indexer Settings Exposure
  author: ProjectDiscoveryAI
  severity: medium
  description: |
    This template checks for the exposure of Sonarr indexer settings which can lead to sensitive information disclosure.

http:
  - raw:
      - |
        GET /sonarr/settings/indexers HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Sonarr"
          - "Indexer"
          - "Settings"