id: whisparr-settings-indexers

info:
  name: Whisparr Settings Indexers Exposure
  author: ProjectDiscoveryAI
  severity: medium
  description: |
    This template checks for exposed Whisparr indexer settings which can lead to sensitive information disclosure.

http:
  - raw:
      - |
        GET /whisparr/settings/indexers HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "Whisparr"
          - "Indexer"
          - "Settings"