id: gocd-cruise-configuration

info:
  name: GoCd Cruise Configuration disclosure
  author: dhiyaneshDk
  severity: high
  description: GoCd Cruise Configuration is exposed.
  reference:
    - https://attackerkb.com/assessments/9101a539-4c6e-4638-a2ec-12080b7e3b50
    - https://blog.sonarsource.com/gocd-pre-auth-pipeline-takeover
    - https://twitter.com/wvuuuuuuuuuuuuu/status/1456316586831323140
  classification:
    cpe: cpe:2.3:a:thoughtworks:gocd:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: thoughtworks
    product: gocd
    shodan-query: http.title:"Create a pipeline - Go" html:"GoCD Version"
  tags: go,gocd,config,exposure,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/go/add-on/business-continuity/api/cruise_config"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "server agentAutoRegisterKey"
          - "webhookSecret"
          - "tokenGenerationKey"
        condition: and
# digest: 490a00463044022064c6180ef9ba8d1a0280c4f7975a0f351c7f3f680dc96f04b7606f1ce750dd9602203479ea116cc4c7687973e3a9185d34a51e7cf633f90542809d3d8ba6d0aaea67:922c64590222798bb761d5b6d8e72950