id: accueil-wampserver

info:
  name: Accueil WAMPSERVER Configuration Page - Detect
  author: tess
  severity: medium
  description: Accueil WAMPSERVER configuration page was detected.
  remediation: Restrict access to the WAMP server configuration page and sub-tools.
  reference:
    - https://www.wampserver.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
    cpe: cpe:2.3:a:wampserver:wampserver:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"Accueil WAMPSERVER"
    product: wampserver
    vendor: wampserver
  tags: exposure,accueil,wampserver,config

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Accueil WAMPSERVER"
          - "Configuration Serveur"
        condition: and

      - type: status
        status:
          - 200
# digest: 490a00463044022041105c62e740af52124ebaaa2c6f6542925702cfd9c89c8a452e83ae4555aa090220664bf912544e84f019451b6b1724bc32c72357a755947786049c29d58686d78a:922c64590222798bb761d5b6d8e72950