id: apache-ozone-conf

info:
  name: Apache Ozone - Exposure
  author: icarot
  severity: info
  description: |
    Detects if path /conf of Apache Ozone web application is exposed.
  classification:
    cpe: cpe:2.3:a:apache:ozone:-:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: apache
    product: ozone
    shodan-query: title:"Apache Ozone"
  tags: tech,ozone,apache,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/conf"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<source>ozone-default.xml</source>'
          - 'ozone'
        condition: and

      - type: word
        part: content_type
        words:
          - 'text/xml'

      - type: status
        status:
          - 200
# digest: 4a0a004730450221009c9f112562d5343f418d5e925a0aabb8a689a0d015e10108464bbbe2993b059002205fa7d9b2187d3f4d740c1e36aa7a4628ef56d6d50093cc51abe251294c4d8594:922c64590222798bb761d5b6d8e72950