id: apache-jspwiki-ip-userenum

info:
  name: Apache JSPWiki - User IP Enumeration
  author: icarot
  severity: low
  description: |
    Enumerates the IP Address and users that is currently accessing an Apache JSPWiki web application, leading open source WikiWiki engine, feature-rich and built around standard JEE components (Java, servlets, JSP).
  classification:
    cpe: cpe:2.3:a:apache:jspwiki:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    verified: true
    vendor: apache
    product: jspwiki
  tags: jspwiki,apache,enumeration

http:
  - method: GET
    path:
      - "{{BaseURL}}/Wiki.jsp?page=SystemInfo"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<b>Active Wiki Users</b>'
          - 'Number of active sessions'
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a004730450220657d247ad5fd23529eea223d299f9128c87a9ac2f2217a77c1fe4cc5fd3b9dc6022100d9143cdeaf7b60e2ef7fb8c8b20653ead6af2999832c704f5b4146c17945b087:922c64590222798bb761d5b6d8e72950