id: appspec-yml-disclosure

info:
  name: Appspec YML/YAML - Detect
  author: dhiyaneshDk
  severity: medium
  description: Appspec YML and YAML files are susceptible to information disclosure.
  reference:
    - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/appsec-yml-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/appspec.yml"
      - "{{BaseURL}}/appspec.yaml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "version:"
          - "os:"
          - "files:"
        part: body
        condition: and

      - type: word
        part: header
        words:
          - "text/html"
        negative: true

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100d7ebdd65da1f33e07e41d0a11374eb762e0fcf32f4dae6c9ca83da546e6579b90220664a16574745d78e4eb5afffde7a941271164e13528753e16f762018883076d9:922c64590222798bb761d5b6d8e72950