id: aws-config

info:
  name: AWS Configuration - Detect
  author: m4lwhere
  severity: medium
  description: AWS config found via /.aws/config.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
  tags: config,exposure,aws,credential

http:
  - method: GET
    path:
      - "{{BaseURL}}/.aws/config"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - 'aws_access_key_id\s*=\s*'
          - 'region\s*=\s*'

      - type: word
        part: body
        words:
          - '[default]'

      - type: status
        status:
          - 200
# digest: 490a004630440220563f117090425a7298c50c18438eb07c148af8b758876d1f6497d62a93a9f6ab022061c7f6e3feaa1a5fff5b96cd766a47522212fced22a82ee29fe0738aa37111e1:922c64590222798bb761d5b6d8e72950