id: aws-credentials

info:
  name: AWS Credentials - Detect
  author: m4lwhere
  severity: high
  description: AWS credentials found via /.aws/credentials endpoint.
  reference:
    - https://aws.amazon.com/blogs/security/what-to-do-if-you-inadvertently-expose-an-aws-access-key/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L
    cvss-score: 9.4
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
  tags: config,exposure,aws,credential

http:
  - method: GET
    path:
      - "{{BaseURL}}/.aws/credentials"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - 'aws_access_key_id\s*=\s*'

      - type: dsl
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
        condition: and

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        regex:
          - "(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"
          - "([a-zA-Z0-9+/]{40})"
# digest: 4a0a00473045022100ff078204d4e6c285b98dd028b8a3372a7e653c7c73a18f9b5724fcc773ca8faa022041ba62835b57cc9ba68676c543ffb7904098d41f321c0fa1f2edd934a9edcbb2:922c64590222798bb761d5b6d8e72950