id: awstats-cgi-bin-detection

info:
  name: AWStats CGI-Bin Detection
  author: msegoviag
  severity: medium
  description: AWStats is a free powerful and featureful tool that generates advanced web, streaming, ftp or mail server statistics, graphically. This log analyzer works as a CGI or from command line and shows you all possible information your log contains, in few graphical web pages.
  reference:
    - https://www.awstats.org/
    - https://www.tenable.com/plugins/nessus/26056
  tags: awstats,cgi,info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/awstats.pl"
    matchers:
      - type: word
        words:
          - "AWStats"
          - "<title>AWStats</title>"
        condition: or
        part: body

      - type: status
        status:
          - 200
