id: awstats-script

info:
  name: AWStats Script Config - Detect
  author: sheikhrishad,msegoviag
  severity: info
  description: AWStats configuration information was detected.
  reference: https://www.awstats.org/docs/awstats_setup.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 4
  tags: config,exposure,awstats

http:
  - method: GET
    path:
      - "{{BaseURL}}/awstats.pl"
      - "{{BaseURL}}/cgi-bin/awstats.pl"
      - "{{BaseURL}}/logs/awstats.pl"
      - "{{BaseURL}}/webstats/awstats.pl"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Do not remove this line"

      - type: word
        part: header
        words:
          - "application/x-perl"

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100873f4ed29b6914ffaca76eef1dc5dcd44863051658d6112b0ee44ca4d8d02e2502202717ad517a5da09d66cb4d00c0475df3e8b046f364c9d7ebcaa8941c3aab4e40:922c64590222798bb761d5b6d8e72950