id: azure-domain-tenant

info:
  name: Microsoft Azure Domain Tenant ID - Detect
  author: V0idC0de
  severity: info
  description: Microsoft Azure Domain Tenant ID was detected.
  reference:
    - https://azure.microsoft.com
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: azure,microsoft,cloud,exposure

http:
  - raw:
      - |
        @Host: https://login.microsoftonline.com:443
        GET /{{Host}}/v2.0/.well-known/openid-configuration HTTP/1.1
        Host: login.microsoftonline.com

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "token_endpoint"

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "\"https:\\/\\/login\\.microsoftonline\\.com\\/([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"
# digest: 490a0046304402202d75a1f0e95fc79125243111bea746e3f5a87d5f482947f1ff9e12d9a799b2d20220171b1d4fafd84902e30631fbbe32706cac8f6185e67a3d51f6e9d352942f55a6:922c64590222798bb761d5b6d8e72950