id: behat-config

info:
  name: Behat Configuration File  - Detect
  author: DhiyaneshDK
  severity: medium
  description: Behat configuration file was detected.
  reference:
    - https://docs.behat.org/en/v2.5/guides/7.config.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"behat.yml"
  tags: exposure,behat,devops,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/behat.yml"
      - "{{BaseURL}}/behat.yml.dist"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'default:'
          - 'paths:'
          - 'suites:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100d9acd07c4418d995ec2d659987fcbaaae466a5955ec9dc77aef31ce791ffd6db02205c715f1a4f4b13ea4cbe8cfe621eb1fea5282f5ccb917115a072dbb32f21e721:922c64590222798bb761d5b6d8e72950