id: blazor-boot

info:
  name: Blazor Boot File Disclosure
  author: freakyclown
  severity: info
  description: Exposed Blazor Boot (a web framework developed by Microsoft) config file.
  reference:
    - https://github.com/freakyclown/Nuclei_templates/blob/main/blazor_server.yaml
  metadata:
    verified: true
    max-request: 1
    github-query: 'blazor.boot.json language:JSON'
  tags: blazor,boot,exposure,config,disclosure

http:
  - method: GET
    path:
      - "{{BaseURL}}/_framework/blazor.boot.json"

    matchers:
      - type: word
        words:
          - 'Blazor'
          - '"config":'
        condition: and

    extractors:
      - type: regex
        part: body
        regex:
          - \"([^"\r\n]+\.dll)\"
# digest: 4a0a0047304502207304478555e570733e99bb85bee9662fcfc1ede8de3ebac0df357053bf8b001d022100877c6612de763da58c6abd76167b270fa354e51c6b1d416d190cdc85767b1f88:922c64590222798bb761d5b6d8e72950