id: codeigniter-env

info:
  name: Codeigniter - .env File Discovery
  author: emenalf
  severity: high
  description: Codeigniter .env file was discovered.
  metadata:
    max-request: 12
  tags: config,exposure,codeigniter

http:
  - method: GET
    path:
      - "{{BaseURL}}{{paths}}"
    payloads:
      paths:
        - "/.env"
        - "/.env.dev.local"
        - "/.env.development.local"
        - "/.env.prod.local"
        - "/.env.production.local"
        - "/.env.local"
        - "/.env.example"
        - "/.env.stage"
        - "/.env.live"
        - "/.env_1"
        - "/.env.old"
        - "/.env_sample"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(?m)^APP_(NAME|ENV|KEY|DEBUG|URL|PASSWORD)"
          - "(?m)^DB_(HOST|PASSWORD|DATABASE)"
        condition: or

      - type: status
        status:
          - 200
# digest: 490a00463044022003fec706b6a7d7a7b307c66293689a37d14521b6de630a287ca37544f8ccf9d102206f335d3c458ea6f52aea57424fd15f31a6eae81334af3cfc7cabc97f14252f15:922c64590222798bb761d5b6d8e72950