id: codeception-config

info:
  name: Codeception YAML Configuration File - Detect
  author: DhiyaneshDk
  severity: low
  description: Codeception YAML configuration file was detected.
  classification:
    cpe: cpe:2.3:a:codeception:codeception:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"codeception.yml"
    product: codeception
    vendor: codeception
  tags: exposure,devops,codeception,config,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/codeception.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "paths:"
          - "settings:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502201dea95b32004a291150d4113d2638624380b8e4bfd901755d4a61bc4ddb7b05f022100a49000a9141535844fde4b04dcfbe4b9a6db6c5de812386f69050c42bc8a2095:922c64590222798bb761d5b6d8e72950