id: collibra-properties

info:
  name: Collibra Properties Exposure
  author: 0xPugal
  severity: high
  description: Detected exposed Collibra Properties.
  reference:
    - https://twitter.com/shaybt12/status/1662431219223605254
  metadata:
    verified: true
    max-request: 3
  tags: exposure,config,collibra-properties,collibra

http:
  - method: GET
    path:
      - "{{BaseURL}}/collibra.properties"
      - "{{BaseURL}}/app/collibra.properties"
      - "{{BaseURL}}/src/collibra.properties"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'collibra.url'
          - 'collibra.port'
          - 'collibra.user'
          - 'collibra.password'
        condition: or

      - type: word
        part: header
        words:
          - "text/plain"
          - "bytes"
        condition: or

      - type: word
        part: header
        words:
          - "text/html"
        negative: true

      - type: status
        status:
          - 200
# digest: 490a00463044022007a2f901f74227edbb32eaceea4325d891f9d763579d541464084dc4765e17b202202bde0b96d1420955b814038a54e6102c289d84285b1b8403400b09d312af49a7:922c64590222798bb761d5b6d8e72950