id: composer-config

info:
  name: Composer Config - Detect
  author: Mahendra Purbia (Mah3Sec_)
  severity: info
  description: Composer configuration file detected.
  reference: https://getcomposer.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 4
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/composer.json"
      - "{{BaseURL}}/composer.lock"
      - "{{BaseURL}}/.composer/composer.json"
      - "{{BaseURL}}/vendor/composer/installed.json"

    matchers:
      - type: dsl
        name: composer.lock
        dsl:
          - "contains(body, 'packages') && contains(tolower(header), 'application/octet-stream') && status_code == 200"

      - type: dsl
        name: composer.json
        dsl:
          - "contains(body, 'require') && contains(tolower(header), 'application/json') && status_code == 200"
# digest: 490a0046304402206ee8e8a2acb0668c99829eb5fcdb1272cfd1fc7880f45a40d1ff632d7430b5f702203e4d8ba8a66bcbeccc5a569ffb201cbc55a19e51822ec8020abecf48bf6aefdc:922c64590222798bb761d5b6d8e72950