id: config-json

info:
  name: Configuration File - Detect
  author: geeknik
  severity: medium
  description: Multiple configuration files were detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 4
    github-query: filename:config.json
  tags: config,exposure,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/config/default.json"
      - "{{BaseURL}}/config.json"
      - "{{BaseURL}}/config/config.json"
      - "{{BaseURL}}/credentials/config.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"api_keys":'
          - '"aws":'
          - '"server":'
        condition: or

      - type: word
        part: header
        words:
          - "text/html"
        negative: true

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100e071fc853a78edf5bca1eabb77ab9c5031ce1731ea1cde1933e4afd8b3be138b022100871e4ac8993a7dffe9bdebe4076815560f889a6b0fec90c61f3795cd39edea12:922c64590222798bb761d5b6d8e72950