id: dockercfg-config

info:
  name: Detect .dockercfg
  author: geeknik
  severity: high
  description: Docker registry authentication data
  metadata:
    max-request: 2
  tags: docker,exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/.dockercfg"
      - "{{BaseURL}}/.docker/config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"email":'
          - '"auth":'
        condition: and

      - type: word
        part: header
        words:
          - "text/plain"

      - type: status
        status:
          - 200
# digest: 4a0a0047304502205967e804a333a139245a9259b6b4ed5f876911fd60439f57b309b1ce355b093f022100a88b4d8b27a1951c79bb0deea60d6f3e62bc2719cef83017dd6726eecc288f97:922c64590222798bb761d5b6d8e72950