id: dompdf-config

info:
  name: DomPDF - Configuration Page
  author: kazet
  severity: low
  description: |
    DOMPDF Configuration page was detected, which contains paths, library versions and other potentially sensitive information
  classification:
    cwe-id: CWE-200
    cpe: cpe:2.3:a:dompdf_project:dompdf:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 6
    fofa-query: title="dompdf - The PHP 5 HTML to PDF Converter"
    product: dompdf
    vendor: dompdf_project
  tags: config,exposure,dompdf

http:
  - method: GET
    path:
      - "{{BaseURL}}/www/setup.php"
      - "{{BaseURL}}/dompdf/dompdf/www/setup.php"
      - "{{BaseURL}}/js/dompdf/www/setup.php"
      - "{{BaseURL}}/portal/application/libraries/dompdf/www/setup.php"
      - "{{BaseURL}}/sites/all/libraries/dompdf/www/setup.php"
      - "{{BaseURL}}/vendor/dompdf/dompdf/www/setup.php"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'HTML to PDF Converter</title>'
          - '<td class="title">DOMPDF_PDF_BACKEND</td>'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502203f203205b87702a29522932f8cc73a3a120365c57d818457e9cf8f9982038133022100895820e8f6893b4594cc05352931594554143e321e27a60b00edbd9665afad2a:922c64590222798bb761d5b6d8e72950