id: editor-exposure

info:
  name: Editor Configuration File - Detect
  author: DhiyaneshDk,daffainfo
  severity: low
  description: Editor configuration file was detected.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"editorconfig"
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.editorconfig"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "= true"
          - "indent_style"
        condition: and

      - type: word
        part: header
        words:
          - "application/json"
          - "text/html"
        negative: true
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100b13d23dfd078d618ad507ac361bbb84473448749fced8b555bddf7f5f52d0e5f02206a33abf679677525d9293d80c0587904566fe76dbb27620585f0e5aa6943c069:922c64590222798bb761d5b6d8e72950
