id: editor-exposure

info:
  name: Editor Configuration File - Detect
  author: DhiyaneshDk,daffainfo
  severity: low
  description: Editor configuration file was detected.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"editorconfig"
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.editorconfig"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "= true"
          - "indent_style"
        condition: and

      - type: word
        part: header
        words:
          - "application/json"
          - "text/html"
        negative: true
        condition: or

      - type: status
        status:
          - 200
# digest: 490a004630440220219105896bd369be0629f9ea3d2090e120d8984167de122e063cad587f073384022067e28be18f9ec9890cd50181a4d61de2240916afd4e4a2452dc2f7cbb4a98e16:922c64590222798bb761d5b6d8e72950