id: exposed-svn

info:
  name: SVN Configuration - Detect
  author: udit_thakkur,dwisiswant0
  severity: medium
  description: SVN configuration was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,svn

http:
  - method: GET
    path:
      - "{{BaseURL}}/.svn/entries"

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "(^\\d\\s*dir|\\.svn-base|has-props|svn:\\/\\/|([\\da-f]{32}[\\S+\\r\\n\\s]+[\\d]{4}-[\\d]{2}-[\\d]{2}T[\\d]{2}:[\\d]{2}:[\\d]{2}.[\\d]{6}Z))"

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/plain"
# digest: 4b0a00483046022100bbc9a922d59b81cce31794da6fd385fc286cc4ef4f81cf6bfcf9d024cf4f45c9022100b56931ed9c6bbd52da376f9bf29ef1d2ec8b47826d630116a9b8f8061009c7b1:922c64590222798bb761d5b6d8e72950