id: exposed-sharepoint-list

info:
  name: Sharepoint List - Detect
  author: ELSFA7110
  severity: medium
  description: Sharepoint list was detected because of improper configuration. An anonymous user can access SharePoint Web Services.
  reference:
    - https://hackerone.com/reports/761158
    - https://hackerone.com/reports/300539
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: hackerone,config,exposure,sharepoint

http:
  - method: GET
    path:
      - "{{BaseURL}}/_vti_bin/lists.asmx?WSDL"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "GetListResponse"
          - "GetList"
        part: body
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450221009e7a2a7dc5435a751de0758039a0c84ee2faa3901adff23ce416857dcd9b981002203c6855508e3e8c7fe11cc5b7b3808b402691ea2d16b869621ec6215f14504d44:922c64590222798bb761d5b6d8e72950