id: exposed-bzr

info:
  name: Bazaar Configuration - Detect
  author: daffainfo
  severity: info
  description: Bazaar configuration was detected.
  reference:
    - http://doc.bazaar.canonical.com/beta/en/user-reference/configuration-help.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.bzr/branch/branch.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "parent_location"
          - "push_location"
        condition: or

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "text/plain"
# digest: 4b0a00483046022100eeca5670400e38c68afdedd0d85e86ac8cde8b756ddc28c6b168abddc72d6a88022100c9057d71fe34bebb56a55d7ae06bbbc49c13ff16d8a2024b34f748bc2dd38664:922c64590222798bb761d5b6d8e72950