id: exposed-darcs

info:
  name: Darcs Configuration - Detect
  author: daffainfo
  severity: info
  description: Darcs configuration was detected.
  reference:
    - http://darcs.net/Using/Configuration#sources
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/_darcs/prefs/binaries"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Binary file regexps"

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100aaaaae1b9de69f29c96650475538485a3429a10fe29fe409a87990b60a19617c02207bdb7240be8e792041a0258b477083abac647f4e2c971d97626dfb43191a6f30:922c64590222798bb761d5b6d8e72950