id: exposed-authentication-asmx

info:
  name: Authentication.asmx - Detect
  author: DhiyaneshDk
  severity: info
  description: Authentication Web Service authentication.asmx file was detected.
  reference:
    - https://www.exploit-db.com/ghdb/6604
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,edb

http:
  - method: GET
    path:
      - "{{BaseURL}}/_vti_bin/Authentication.asmx?op=Mode"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Authentication Web Service"
        part: body

      - type: status
        status:
          - 200
# digest: 490a004630440220130083f818d4643fb4c5ac72ccb7dbae1858df13de8e5970787681ad1a6b1919022004f491c52db2e02f6978574907aedb01869ea81be368d30e6a2d3fa84177f8b8:922c64590222798bb761d5b6d8e72950