id: exposed-bitkeeper

info:
  name: BitKeeper Configuration - Detect
  author: daffainfo
  severity: low
  description: BitKeeper configuration was detected.
  reference:
    - https://www.bitkeeper.org/man/config-etc.html
  metadata:
    max-request: 1
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/BitKeeper/etc/config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "BitKeeper configuration"
          - "logging"
          - "email"
          - "description"
        condition: and

      - type: status
        status:
          - 200
# digest: 490a0046304402206443fd2eb6159bc486902367d8b468860acb2cd79b62e76f82b1637b0267e24b02207446283d7d136c5a2b90fa3fdcde36638cf00c1ca094d521e105739b4e48978e:922c64590222798bb761d5b6d8e72950