id: filestash-admin-config

info:
  name: Filestash Admin Password Configuration
  author: DhiyaneshDK
  severity: high
  description: |
    Filestash is susceptible to the Admin Password Configuration page exposure due to misconfiguration.
  classification:
    cpe: cpe:2.3:a:filestash:filestash:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: filestash
    product: filestash
    shodan-query: html:"<title>Admin Console</title>"
  tags: exposure,filestash,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/admin/setup"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<title>Admin Console</title>'
          - 'component-loader'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450220301c84e895deb5ebd59b66d3d64755cd5510fd2042e0e56ca294bdd260369e7f022100e25a19af2abef8ee2c647a6120bd243696b7c5823b11ed524925af55e843a173:922c64590222798bb761d5b6d8e72950