id: ftp-credentials-exposure

info:
  name: FTP Credentials Exposure
  author: pikpikcu
  severity: high
  description: FTP credentials were detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
    cpe: cpe:2.3:a:wftpserver:wing_ftp_server:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    google-query: inurl:"/ftpsync.settings"
    product: wing_ftp_server
    vendor: wftpserver
  tags: config,ftp,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/ftpsync.settings"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "FTPSync"
          - "overwrite_newer_prevention"
          - "default_folder_permissions"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100f98524346e9cca4fcc130e7a9131f0b2cadf0042d96c9ddc237ccba478fcdc3702204edbe8d14fe7fab173301dede059d4f9330be915b4423da7984bdaf4473065a6:922c64590222798bb761d5b6d8e72950