id: gcloud-config-default

info:
  name: Google Cloud Default Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Google Cloud default configuration was detected.
  reference: https://cloud.google.com
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:google:cloud_platform:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"access_tokens.db"
    product: cloud_platform
    vendor: google
  tags: google,cloud,devops,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/configurations/config_default"
      - "{{BaseURL}}/.config/gcloud/configurations/config_default"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '[core]'
          - 'account'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100976da29bc8bc4a6e8c069cfe09456a93897fb8807b11c4e4905ae39fc673892d0220603f73b121ab0d0367e4c64c638c411ea6e31ded90539fb2f2ddf739901d503b:922c64590222798bb761d5b6d8e72950