id: git-config-credentials

info:
  name: Git Configuration Credentials - Detect
  author: m4lwhere
  severity: high
  description: Git configuration was detected via the pattern /.git/config and contains credentials.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L
    cvss-score: 9.4
    cwe-id: CWE-200
  tags: config,git,exposure
  metadata:
    max-request: 1

http:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[credentials]"
          - "[core]"
        part: body
        condition: or

      - type: regex
        regex:
          - "AUTHORIZATION: basic"
          - "url ?= ?https?://(.*:.*)@"
        condition: or
        part: body

      - type: dsl
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
        condition: and

      - type: status
        status:
          - 200
    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "url ?= ?https?://(.*:.*)@"
          - "AUTHORIZATION: basic (.*)"
          - "pass = (.*)"
