id: git-config

info:
  name: Git Configuration - Detect
  author: pdteam,pikpikcu,Mah3Sec_,m4lwhere
  severity: medium
  description: Git configuration was detected via the pattern /.git/config and log file on passed URLs.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,git,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.git/config"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "[credentials]"
          - "[core]"
        condition: or

      - type: dsl
        dsl:
          - "!contains(tolower(body), '<html')"
          - "!contains(tolower(body), '<body')"
        condition: and

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "url ?= ?https?://(.*:.*)@"
          - "AUTHORIZATION: basic (.*)"
          - "pass = (.*)"
# digest: 4b0a00483046022100bf9fa80a5abbdeb25e8d65f1c20c0c4386f12493441dc2a1948f20c63f396c2f022100dc34f83847352d418fdccaf9f35b1f1dd1a34fb8d6c63bd382328a7e3e446bca:922c64590222798bb761d5b6d8e72950