id: gmail-api-client-secrets

info:
  name: GMail API - Detect
  author: geeknik
  severity: info
  description: GMail API was detected.
  reference: https://developers.google.com/gmail/api/auth/web-server
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/client_secrets.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "client_id"
          - "auth_uri"
          - "token_uri"
        condition: and

      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - "application/json"
# digest: 4a0a0047304502206d249e198639dd61f6f042a426a41a91d3ebbd6d03c7e10b397a5ecff705f0dd022100e8d25e8d81002a12d6c449aa33831800939c42608f304a29a7a2f7fb82340ae7:922c64590222798bb761d5b6d8e72950