id: gruntfile-exposure

info:
  name: Gruntfile Config - Detect
  author: sbani
  severity: info
  description: Gruntfile configuration information was detected.
  reference:
    - https://gruntjs.com/sample-gruntfile
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/Gruntfile.js"
      - "{{BaseURL}}/Gruntfile.coffee"

    host-redirects: true
    max-redirects: 2

    matchers-condition: and
    matchers:
      - type: word
        part: body
        condition: and
        words:
          - "module.exports"
          - "grunt"

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100dd9d71faafee8bf2f7ab91d7f5d793aa607aade1d22dc76d92fc8321a06f112a022100d69ff4eee4dd474a1e686bad2a0df21a806b90b0cecb6be87c2182af2d604d2d:922c64590222798bb761d5b6d8e72950