id: guard-config

info:
  name: Guardfile Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Guardfile configuration information was detected.
  reference:
    - https://github.com/guard/guard
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Guardfile"
  tags: exposure,file,guard,config

http:
  - method: GET
    path:
      - '{{BaseURL}}/Guardfile'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'guard :'
          - 'end'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a004830460221008e48d18d4ee1cd983b0f571ab074d7a2b5afd4de258836b50358d8905d8680fa022100a7d24fc1de1ba063f787689b4773983d57cc4677f5db11202c2ff525fb19895d:922c64590222798bb761d5b6d8e72950