id: hikvision-info-leak

info:
  name: Hikvision Configuration File - Detect
  author: pikpikcu
  severity: medium
  description: Hikvision configuration file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: exposure,config,hikvision

http:
  - method: GET
    path:
      - '{{BaseURL}}/config/user.xml'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<user name='
          - 'password='
        condition: and

      - type: word
        words:
          - "text/xml"
        part: header
# digest: 490a0046304402205483709e727e8e9669755a2d2a3fe7a5c25870e0e3db42a7dd19c0303cbc3c0f02204db0fab1a0c764c768bad56fb62f92653df25c7d0b40998cd17357f57ad27e5a:922c64590222798bb761d5b6d8e72950