id: htpasswd-detection

info:
  name: Apache htpasswd Config - Detect
  author: geeknik
  severity: high
  description: Apache htpasswd configuration was detected.
  reference: https://httpd.apache.org/docs/current/programs/htpasswd.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.htpasswd"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - ":{SHA}"
          - ":$apr1$"
          - ":$2y$"
        condition: or

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100f02a5525f2be37a6db7c91be10d32d90d02d4ee703c717853c61ededd631d6c4022055316228af2ec1d3d5c77fb50b1b4b3f83e6ccf0e511af5a66ffba1ffc36a4c7:922c64590222798bb761d5b6d8e72950