id: httpd-config

info:
  name: Apache httpd Config File - Detect
  author: sheikhrishad
  severity: info
  description: Apache httpd configuration information was detected.
  reference: https://httpd.apache.org/docs/current/configuring.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,httpd

http:
  - method: GET
    path:
      - "{{BaseURL}}/httpd.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "LoadModule"
          - "# LoadModule"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450221008b851435698e9a4f8f52638f06a2623a1fb6585ba9fa4011793c50ec54eaafb302204b95df0f2a64cfcedbd9d5986ff4329835ce92aee87d5288ec3c901db45ee293:922c64590222798bb761d5b6d8e72950