id: java web config files

info:
  name: java web config files
  author: w8ay
  severity: low
  description: java web config files was exposed.
  tags: exposure,java,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/WEB-INF/web.xml"
      - "{{BaseURL}}/WEB-INF/applicationContext.xml"
      - "{{BaseURL}}/WEB-INF/applicationContext-slave.xml"
      - "{{BaseURL}}/WEB-INF/config.xml"
      - "{{BaseURL}}/WEB-INF/spring.xml"
      - "{{BaseURL}}/WEB-INF/struts-config.xml"
      - "{{BaseURL}}/WEB-INF/struts-front-config.xml"
      - "{{BaseURL}}/WEB-INF/struts/struts-config.xml"
      - "{{BaseURL}}/WEB-INF/classes/spring.xml"
      - "{{BaseURL}}/WEB-INF/classes/struts.xml"
      - "{{BaseURL}}/WEB-INF/classes/struts_manager.xml"
      - "{{BaseURL}}/WEB-INF/classes/conf/datasource.xml"
      - "{{BaseURL}}/WEB-INF/classes/data.xml"
      - "{{BaseURL}}/WEB-INF/classes/config/applicationContext.xml"
      - "{{BaseURL}}/WEB-INF/classes/applicationContext.xml"
      - "{{BaseURL}}/WEB-INF/classes/conf/spring/applicationContext-datasource.xml"
      - "{{BaseURL}}/WEB-INF/config/db/dataSource.xml"
      - "{{BaseURL}}/WEB-INF/spring-cfg/applicationContext.xml"
      - "{{BaseURL}}/WEB-INF/dwr.xml"
      - "{{BaseURL}}/WEB-INF/classes/hibernate.cfg.xml"
      - "{{BaseURL}}/WEB-INF/classes/rabbitmq.xml"
      - "{{BaseURL}}/WEB-INF/conf/activemq.xml"
      - "{{BaseURL}}/server.xml"
      - "{{BaseURL}}/conf/web.xml"
      - "{{BaseURL}}/conf/server.xml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<?xml'

      - type: word
        part: header
        words:
          - "application/xml"
          - "text/xml"
        condition: or

      - type: status
        status:
          - 200