id: jetbrains-datasource

info:
  name: Jetbrains IDE DataSources Config - Detect
  author: FlorianMaak
  severity: info
  description: Jetbrains IDE DataSources configuration information was detected.
  reference: https://www.jetbrains.com
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,jetbrains

http:
  - method: GET
    path:
      - "{{BaseURL}}/.idea/dataSources.xml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DataSourceManagerImpl"
        part: body

      - type: status
        status:
          - 200
# digest: 490a00463044022002e9fc3a6196b20d7963a9262d2532edd0ec19cf73729275564715ecb5226dab02203a92bbb7f5bec6bc2597123e4660fe614d74cd395ad05457fa9f53c661264f69:922c64590222798bb761d5b6d8e72950