id: jkstatus-manager

info:
  name: JK Status Manager - Detect
  author: pdteam,DhiyaneshDk
  severity: low
  description: |
    Exposed JKStatus manager which is a web-based tool that allows administrators to monitor and manage the connections between the Apache HTTP Server and the Tomcat application server.
  reference:
    - https://github.com/PortSwigger/j2ee-scan/blob/master/src/main/java/burp/j2ee/issues/impl/JKStatus.java
  classification:
    cpe: cpe:2.3:a:apache:tomcat:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 8
    vendor: apache
    product: tomcat
    shodan-query: html:"JK Status Manager"
  tags: config,jk,status,exposure

http:
  - method: GET

    headers:
      X-Forwarded-For: "127.0.0.1"
    path:
      - "{{BaseURL}}"
      - "{{BaseURL}}/status"
      - "{{BaseURL}}/jkstatus"
      - "{{BaseURL}}/jkstatus-auth"
      - "{{BaseURL}}/jk-status"
      - "{{BaseURL}}/jkmanager"
      - "{{BaseURL}}/jkmanager-auth"
      - "{{BaseURL}}/jdkstatus"

    stop-at-first-match: true
    matchers:
      - type: word
        words:
          - "JK Status Manager"
# digest: 4b0a004830460221009e5c5a8636ec58fedc6be3ca69cadc65d1e27e858013d4178efac927265f1675022100a122c482b77ee4eddd7a9594049cc34a1a45bf54c2467918e267e144f7c19103:922c64590222798bb761d5b6d8e72950