id: jsconfig-json

info:
  name: Visual Studio Code jsconfig.json - Detect
  author: DhiyaneshDk
  severity: info
  description: Visual Studio Code jsconfig.json was detected.
  reference:
    - https://code.visualstudio.com/docs/languages/jsconfig
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"jsconfig.json"
  tags: devops,exposure,jsconfig,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/jsconfig.json"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"compilerOptions": {'
          - '"typeAcquisition": {'
        condition: or

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100c3c56c2f3c1691cc376f8d1dfd87bac6a368665a4658675414d89912968c7929022100a0a955e3aeb48cc37abe77199912b0e0a528c28ddc2281b974db4c23fc3f0faa:922c64590222798bb761d5b6d8e72950