id: kyan-credential-exposure

info:
  name: Kyan Credential - Exposure
  author: pikpikcu
  severity: medium
  description: Kyan Network login panel was detected. Password and other credential theft is possible via accessing this panel.
  reference:
    - https://mp.weixin.qq.com/s/6phWjDrGG0pCpGuCdLusIg
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: kyan,exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/hosts"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "UserName="
          - "Password="
        condition: and

      - type: word
        part: header
        words:
          - "text/plain"

      - type: status
        status:
          - 200
# digest: 4a0a00473045022055027eb3c39723cf0fc212af177af8924b506873447a268c79d015e67b68f8140221009dba432c8cfc4b4f398f412dbfd875a2a5f850d8793a8e2534cd4a6ac7301e1a:922c64590222798bb761d5b6d8e72950