id: lvmeng-uts-disclosure

info:
  name: Lvmeng - UTS Disclosure
  author: pikpikcu
  severity: high
  description: Lvmeng UTS was discovered.
  metadata:
    max-request: 1
  tags: config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/webapi/v1/system/accountmanage/account"

    headers:
      Content-Type: application/json

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "application/json"
        condition: and
        part: header

      - type: word
        words:
          - "password"
          - "nsfocus_uts"
          - "MANAGER_IP"
        condition: and
        part: body
# digest: 490a00463044022012bd392fd47cd3b530514fcae4e5f9d640e663d65666213b8c0768bea85402dc022049e7f3191f89abecd2137974c963ce0b1352e5415421b6476801624b5a8b4770:922c64590222798bb761d5b6d8e72950