id: magicinfo-config-file

info:
  name: Samsung MagicINFO Configuration File
  author: s4e-io
  severity: info
  description: |
    Detects exposure of Samsung MagicINFO configuration file (/MagicInfo/config.js),and extracts magicInfoFrontEndVersion.
  reference:
    - https://www.samsung.com/de/business/display-solutions/magicinfo/
  metadata:
    vendor: samsung
    product: magicinfo_9_server
    shodan-query: title:"MagicINFO"
    fofa-query: title:"MagicINFO"
  tags: config,exposure,magicinfo

http:
  - method: GET
    path:
      - "{{BaseURL}}/MagicInfo/config.js"

    matchers:
      - type: dsl
        dsl:
          - 'contains_all(body, "globalConfig", "MagicINFO", "samsung")'

    extractors:
      - type: regex
        name: magicinfo_version
        group: 1
        part: body
        regex:
          - '"magicInfoFrontEndVersion":\s*"([^"]+)"'
