id: neo4j-neodash-configexposed

info:
  name: Neo4j Neodash Detection
  author: icarot
  severity: medium
  description: |
    Detects the file config.json from Neo4j Neodash web application, it contains information about DB connection with Neo4J.
  classification:
    cpe: cpe:2.3:a:neo4j:*:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: neo4j
    product: neodash
  tags: config,exposure,credential,neodash,neo4j

http:
  - method: GET
    path:
      - "{{BaseURL}}/config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'standaloneHost'
          - 'standalonePort'
          - 'standaloneDatabase'
        condition: and

      - type: status
        status:
          - 200
    extractors:
      - type: json
        name: config.json
        part: body
        json:
          - '.standaloneHost,.standalonePort,.standaloneDatabase,.standaloneUsername,.standalonePassword,.standaloneDashboardName'
