id: neo4j-neodash-config

info:
  name: Neo4j Neodash Config - Exposure
  author: icarot
  severity: medium
  description: |
    Detects the file config.json from Neo4j Neodash web application, it contains information about DB connection with Neo4J.
  classification:
    cpe: cpe:2.3:a:neo4j:*:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    verified: true
    vendor: neo4j
    product: neodash
    shodan-query: title:"NeoDash"
  tags: config,exposure,neodash,neo4j

http:
  - method: GET
    path:
      - "{{BaseURL}}/config.json"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'standaloneHost'
          - 'standalonePort'
          - 'standaloneDatabase'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200

    extractors:
      - type: json
        name: config
        part: body
        json:
          - '.standaloneDatabase,.standaloneUsername,.standalonePassword'
# digest: 4a0a004730450220262b2947ade195c7bfbee7a1a686f5e5a86cce91675d3bcc038c03e86330824a0221009f54b77a59cc785dcc14c52825fb5f73a1c84bdc8528e758f0d4aa9cd770f81b:922c64590222798bb761d5b6d8e72950