id: netrc

info:
  name: Netrc - Config File Discovery
  author: geeknik
  severity: high
  description: Netrc configuration file was discovered.
  reference:
    - https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html
  metadata:
    max-request: 2
  tags: netrc,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/.netrc"
      - "{{BaseURL}}/_netrc"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: regex
        regex:
          - "machine [0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\\.?"

      - type: word
        words:
          - "login "
          - "password "
        condition: and

      - type: word
        part: header
        words:
          - "text/html"
        negative: true

    extractors:
      - type: regex
        part: body
        regex:
          - "machine [0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\\.?"
# digest: 4b0a00483046022100abc5039cc95c69f718944f572a6f8225a1a480098dbb8499f40d750bf70c0b7c022100dea8678ef15b647f8731a747cc4f0c41c3e938028df591890586b0ef88b0d973:922c64590222798bb761d5b6d8e72950