id: nginx-config

info:
  name: Nginx Config - Detect
  author: sheikhrishad,geeknik
  severity: info
  description: Nginx configuration information was detected.
  reference:
    - https://nginx.org/en/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,nginx

http:
  - method: GET
    path:
      - "{{BaseURL}}/nginx.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "html>"
        negative: true

      - type: word
        words:
          - "server"
          - "listen"
          - "server_name"
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a004830460221009258f50805ec09c6ee249b25ecba70efbd22e7850ebb18ef8743ba75ae0cda58022100a7b2910590c508e955226930a118e165c63f2f731916cc7638268543b724245b:922c64590222798bb761d5b6d8e72950