id: phalcon-framework-source

info:
  name: Phalcon Framework - Source Code Leakage
  author: philippedelteil
  severity: high
  description: Phalcon Framework source code was discovered.
  metadata:
    max-request: 1
  tags: exposure,debug,phalcon

http:
  - method: GET
    path:
      - "{{BaseURL}}/anything_here"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Phalcon Framework"
          - "AnythingHereController"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022061b976d683705c4d8b1d8cad5b2af355b3dccf36b22ef5442f35d3feb591cc28022100a3097550cb86e9c4151c176b55150392a7e81d612abbe7889f9ec2f163cdfa62:922c64590222798bb761d5b6d8e72950