id: phpsec-config

info:
  name: phpspec Config - Detect
  author: DhiyaneshDK
  severity: info
  description: phpspec configuration information was detected.
  reference: https://phpspec.net/en/stable/cookbook/configuration.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"phpspec.yml"
  tags: exposure,phpsec,php,devops,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/.phpspec.yml"
      - "{{BaseURL}}/phpspec.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'suites:'
          - 'main:'
          - 'namespace:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100dc96cc12ca2260d56d2c16b66d127d8e9b2236fd80a200d7cb6ef308057ac15802203a3c7e167648bebff2d8a9dc0eb8a067312d73e4ffd1133600e86eaaa367149a:922c64590222798bb761d5b6d8e72950