id: phpstan-config

info:
  name: PHPStan Configuration Page - Detect
  author: DhiyaneshDK
  severity: info
  description: PHPStan configuration page was detected.
  reference: https://phpstan.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"phpstan.neon"
  tags: devops,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpstan.neon"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'parameters:'

      - type: word
        part: header
        words:
          - "text/html"
          - "application/javascript"
        negative: true

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100c077d02e490da8c51f94b724008f54a1071238872bd27d44ccb039f321435269022100cbc948f5e49e615d5e995dd2d03a7bb11389d5b742cc4c5eded21bf3790e3b43:922c64590222798bb761d5b6d8e72950