id: phpsysinfo-exposure

info:
  name: phpSysInfo Exposure
  author: fpatrik
  description: "phpSysInfo: a customizable PHP script that displays information about your system nicely"
  severity: low
  tags: config,exposure,phpsysinfo
  reference: https://phpsysinfo.github.io/phpsysinfo/
  metadata:
    max-request: 1

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpsysinfo/index.php?disp=bootstrap"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>phpSysInfo'
          - 'Hardware Information'
        condition: and
      - type: status
        status:
          - 200
