id: platformio-ini

info:
  name: Platformio Config File Disclosure
  author: DhiyaneshDK
  severity: medium
  description: “platformio.ini” (Project Configuration File) was detected.
  reference:
    - https://docs.platformio.org/en/stable/projectconf/index.html
  metadata:
    max-request: 1
    verified: "true"
    github-query: '[platformio] language:INI'
  tags: config,exposure,platformio

requests:
  - method: GET
    path:
      - "{{BaseURL}}/platformio.ini"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[platformio]"
          - "platform ="
          - "board ="
        condition: and

      - type: status
        status:
          - 200
