id: platformio-ini

info:
  name: Platformio Config File Disclosure
  author: DhiyaneshDK
  severity: low
  description: “platformio.ini” (Project Configuration File) was detected.
  reference:
    - https://docs.platformio.org/en/stable/projectconf/index.html
  metadata:
    verified: true
    max-request: 1
    google-query: inurl:"/platformio.ini"
    github-query: '[platformio] language:INI'
  tags: config,exposure,platformio

http:
  - method: GET
    path:
      - "{{BaseURL}}/platformio.ini"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[platformio]"
          - "platform ="
          - "board ="
        condition: and

      - type: status
        status:
          - 200
# digest: 490a00463044022030105f6a9c10050144820e5ad6ab925b3a4201703fbbadeff446b1f44c879a9802200d6a1c5bb8360ab337d9828992c8cbae8cd789f24b1e310f93dbabe173d5a770:922c64590222798bb761d5b6d8e72950