id: pre-commit-config

info:
  name: Pre-commit Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Pre-commit configuration file was detected.
  reference: https://pre-commit.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
  tags: exposure,devops,config,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/.pre-commit-config.yaml"
      - "{{BaseURL}}/pre-commit-config.yaml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "repos:"
          - "hooks:"
          - "rev:"
        condition: and

      - type: status
        status:
          - 200
# digest: 490a0046304402204ddb388fb8be408927d8125464df77ac14b34f9de399bf682a36228fbf2d157d02207a2dacce15f20e5dc2629f2675cd92ecfb55ebd17d39c83bb2fb3fcbb1adc5b9:922c64590222798bb761d5b6d8e72950