id: procfile-config

info:
  name: Procfile Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Procfile configuration information was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Procfile"
  tags: devops,exposure,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/Procfile"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '^web:'

      - type: status
        status:
          - 200
# digest: 490a0046304402202f4f35c16c1f07c1151fc3884573fbf6e3da63dce7959d39eccf6081dfdd469602203ff1e667cea92a09c868a7e6d7188fb7f71c3a28fff31f9bc96da0b6aff6083d:922c64590222798bb761d5b6d8e72950