id: protractor-config

info:
  name: Protractor Configuration Exposure - Detect
  author: DhiyaneshDK
  severity: low
  description: |
    Protractor configuration file was detected.
  reference:
    - https://www.protractortest.org/#/api-overview
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    max-request: 1
    verified: true
    shodan-query: html:"protractor.conf.js"
  tags: devops,exposure,protractor,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/protractor.conf.js"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'exports.config'
          - 'capabilities:'
        condition: and

      - type: word
        part: header
        words:
          - "application/javascript"

      - type: status
        status:
          - 200
