id: pubspec-config

info:
  name: Pubspec YAML Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Pubspec YAML configuration file was detected.
  reference:
    - https://docs.flutter.dev/development/tools/pubspec
    - https://xeladu.medium.com/the-flutter-pubspec-yaml-in-detail-eee5729d9df7
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"pubspec.yaml"
  tags: exposure,devops,pubsec,config,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/pubspec.yaml"
      - "{{BaseURL}}/assets/pubspec.yaml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "version:"
          - "environment:"
          - "dependencies:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502201a1f9b4793e5e9e5ba441d200f58f28d6aad850dbb57b6686f2a2f06625410e9022100ca59cefa0bbf547cc19572b32b813f5983b1a87d7c7571fe713763a0d1de8f38:922c64590222798bb761d5b6d8e72950