id: pyproject-toml

info:
  name: pyproject.toml Configuration - Detect
  author: DhiyaneshDK
  severity: info
  description: pyproject.toml configuration was detected.
  reference: https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"pyproject.toml"
  tags: exposure,pyproject,pip,devops,cicd

http:
  - method: GET
    path:
      - "{{BaseURL}}/pyproject.toml"

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - "[tool.black]"
          - "exclude ="
        condition: and

      - type: word
        part: body
        words:
          - "[tool.poetry]"
          - "name ="
        condition: and
# digest: 490a0046304402201f6c22720343431bf503b731db6cae3747a2b52c7d59a2430f7ab7fab80daf0e02205715be8fff042276110ff550da4c527df73b9201d0ae1183814f5bf2968594f0:922c64590222798bb761d5b6d8e72950