id: qdpm-info-leak

info:
  name: qdPM 9.2 - DB Credentials Exposure
  author: gy741
  severity: high
  description: qdPM 9.2 database credentials were discovered.
  reference:
    - https://www.exploit-db.com/exploits/50176
  metadata:
    max-request: 1
  tags: qdpm,exposure,edb

http:
  - method: GET
    path:
      - '{{BaseURL}}/core/config/databases.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'dsn:'
          - 'username:'
          - 'password:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100a3d4db87a2515e9fde8944c307d852ea538da2b8d39e70a310d1e0b430dbcb13022100db07cb2cb0c92f4bf815366d8dd67e749a90bab763836ad55962d8e6cf916583:922c64590222798bb761d5b6d8e72950