id: rails-database-config

info:
  name: Ruby on Rails Database Configuration File - Detect
  author: pdteam,geeknik
  severity: high
  description: Ruby on Rails database configuration file was detected, which may contain database credentials.
  reference: https://guides.rubyonrails.org/configuring.html#configuring-a-database
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,rails

http:
  - method: GET
    path:
      - "{{BaseURL}}/config/database.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "adapter:"
          - "database:"
          - "production:"
        condition: and
        part: body

      - type: status
        status:
          - 200
# digest: 4a0a004730450220761c58a20d292d1d9c1f032900fa2cf3c8417e2d977959b04d8a51e4ced06c18022100b6d1184c66ed5b08182e20877af9f026cabfa633cafb241f5d4dd14e5ad754dd:922c64590222798bb761d5b6d8e72950