id: rakefile-disclosure

info:
  name: Rakefile - File Disclosure
  author: DhiyaneshDK
  severity: info
  description: |
    Rakefile configuration file was detected.
  reference:
    - https://ruby.github.io/rake/doc/rakefile_rdoc.html
  classification:
    cpe: cpe:2.3:a:ruby-lang:ruby:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: ruby-lang
    product: ruby
    shodan-query: html:"Rakefile"
  tags: devops,exposure,rakefile,config,ruby,rails

http:
  - method: GET
    path:
      - "{{BaseURL}}/Rakefile"

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - 'application.load_tasks'
          - 'config/application'
        condition: and
        case-insensitive: true

      - type: word
        part: body
        words:
          - 'require'
          - 'desc'
          - 'task :'
        condition: and
# digest: 4a0a00473045022063d6fd591c838a71f1b21aa3e4b800727e8358fb2f7247a9ebff7276c86e2903022100e7c88f6670e14c7f82baf193a88d4c0ef05180d8e64af41e86fc4febdee31e7b:922c64590222798bb761d5b6d8e72950