id: ruijie-information-disclosure

info:
  name: Ruijie Login Panel - Detect
  author: pikpikcu
  severity: high
  description: Ruijie login panel was detected and leaks authentication credentials.
  reference:
    - https://www.ruijienetworks.com/
    - https://www.cnblogs.com/cHr1s/p/14499858.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: ruijie,config,exposure

http:
  - method: GET
    path:
      - '{{BaseURL}}/login.php'

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '"role":"super_admin","name":"(.*)","password":"(.*)"'
        part: body
        condition: and

      - type: status
        status:
          - 200
# digest: 490a004630440220129fb42bd9044410deb0b8faed82054bca5fa4b5278ae4cf6bbb2ecfb24ed743022049d6ac09a5ac2622f8eebc19aa64137458c0c2c7bd3f419b0df44db2341c514a:922c64590222798bb761d5b6d8e72950