id: sftp-deployment-config

info:
  name: Atom SFTP Configuration File - Detect
  author: geeknik
  severity: high
  description: |
    Atom SFTP deployment configuration file was detected. File contains server details and credentials.
  reference:
    - https://atom.io/packages/sftp-deployment
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    github-query: filename:deployment-config.json sftp
  tags: sftp,atom,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/deployment-config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"host":'
          - '"username":'
          - '"password":'
          - '"remotePath":'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100b573728cecfe135a5d95a3f7d4ecb9f7169c9cfe7bb532af384476323449fdbc022035c6f603cc5f79298c4e67ca8b587978b5b934b9dbde5733be42eb0463b2c318:922c64590222798bb761d5b6d8e72950