id: snoop-servlet

info:
  name: Snoop Servlet - Information Disclosure
  author: omranisecurity
  severity: low
  description: |
    The Snoop Servlet returns information about the HTTP request itself and sometimes. It could help an attacker to prepare more advanced attacks.
  reference:
    - https://www.acunetix.com/vulnerabilities/\web/snoop-servlet-information-disclosure/
  metadata:
    max-request: 1
    shodan-query: title:"Snoop Servlet"
    fofa-query: title="Snoop Servlet"
  tags: config,exposure,snoop,snoop-servlet

http:
  - method: GET
    path:
      - "{{BaseURL}}/snoop"

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "Snoop Servlet - Request/Client Information")'
        condition: and
# digest: 490a0046304402205b655306119792c916457ce8666965be543b5764ca2db14bf6ba7b511bacb66502202dc100fb251d17545114e44b28d80220df11ee88dcadb0eecb822d310343b218:922c64590222798bb761d5b6d8e72950