id: ssh-authorized-keys

info:
  name: SSH Authorized Keys File - Detect
  author: geeknik
  severity: medium
  description: SSH authorized keys file was detected.
  reference:
    - https://www.ssh.com/academy/ssh/authorized-key
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure,ssh

http:
  - method: GET
    path:
      - "{{BaseURL}}/.ssh/authorized_keys"
      - "{{BaseURL}}/_/.ssh/authorized_keys"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ssh-dss"
          - "ssh-ed25519"
          - "ssh-rsa"
          - "ecdsa-sha2-nistp256"
        condition: or

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100f277b20818b0ec9da24bf557323b24d6493b49a129c01b2243f794ab78eb76560220340dd2c0a6aa8a4d5e369d00340c6520b18141f24dccc694fe402d1e13ffdd7e:922c64590222798bb761d5b6d8e72950