id: stestr-config

info:
  name: Stestr Configuration File - Detect
  author: Hardik-Solanki
  severity: info
  description: Stestr configuration file was detected.
  reference:
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
    - https://stestr.readthedocs.io/en/latest/MANUAL.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    github-query: filename:stestr.conf
  tags: exposure,stestr,config,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.stestr.conf"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '[DEFAULT]'
          - 'test_path='
        condition: and

      - type: status
        status:
          - 200
# digest: 490a004630440220583cded827c66c33c32ab80b7aad116e8f0f97749f5a8f7745def8c2c49daa3f022022f72a592cfc355f8dde14f80712da62e724dfc60559ac245e14d55e13d58ba6:922c64590222798bb761d5b6d8e72950