id: symfony-database-config

info:
  name: Symfony Database Configuration File - Detect
  author: pdteam,geeknik
  severity: high
  description: Symfony database configuration file was detected and may contain database credentials.
  reference: https://symfony.com/legacy/doc/reference/1_3/en/07-Databases
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,symfony

http:
  - method: GET
    path:
      - "{{BaseURL}}/config/databases.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "text/html"
        negative: true

      - type: status
        status:
          - 200

      - type: word
        words:
          - "class:"
          - "param:"
        condition: and
        part: body
# digest: 4a0a00473045022100ab8f606e8f9e46dc54d0e55bb66f9d4edaecd30b1566ac9354318c89f82f577802201e8f9aaf9ebdc2a5827c4e79a6052d6c6af0949afba44ecb32e9527a665ceb6d:922c64590222798bb761d5b6d8e72950