id: symfony-profiler

info:
  name: Symfony Profiler - Detect
  author: pdteam
  severity: high
  description: Symfony profiler was detected.
  reference: https://symfony.com/doc/current/profiler.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
    cpe: cpe:2.3:a:sensiolabs:symfony:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    shodan-query: http.html:"symfony Profiler"
    product: symfony
    vendor: sensiolabs
  tags: config,exposure,symfony

http:
  - method: GET
    path:
      - "{{BaseURL}}/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/app_dev.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/index.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/index_dev.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/dev.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/debug.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/_debug/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/web/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/public/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/frontend_dev.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/backend_dev.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/api_dev.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/app.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/app_test.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/test.php/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/symfony/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/debug/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/dev/_profiler/empty/search/results?limit=10"
      - "{{BaseURL}}/profiler/empty/search/results?limit=10"

    stop-at-first-match: true
    matchers:
      - type: word
        part: body
        words:
          - "Symfony Profiler"
          - "<title>Profiler</title>"
          - "Symfony-Debug-Toolbar"
# digest: 4b0a00483046022100e75c730f939f973e0ffc751442b7541f7d3a91b8f1aa46fa62d615d47de60b1e02210096bcb0044029b4527bc971b291643f11f7c55273d6b463b0a97cb1bd262d3ec2:922c64590222798bb761d5b6d8e72950