id: tox-ini

info:
  name: Tox Configuration File - Detect
  author: geeknik
  severity: info
  description: Tox configuration file was detected.
  reference: https://tox.wiki/en/latest/config.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"tox.ini"
  tags: exposure,config,tox

http:
  - method: GET
    path:
      - "{{BaseURL}}/tox.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "[tox]"
          - "[testenv]"
        condition: and

      - type: word
        part: header
        words:
          - "application/octet-stream"

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100926e5faf98d58a3c711897fbb893b33c84a6f73dd9081845473e9229800a0d6d022100f3ad56835bbafc3f1d1b090470bc3ef5ad46c59908701004c8b5cf4f82e17dc1:922c64590222798bb761d5b6d8e72950