id: vbulletin-fpd

info:
  name: vBulletin - Full Path Disclosure (FPD)
  author: MaStErChO
  severity: info
  reference:
    - https://github.com/OWASP/vbscan/blob/master/modules/pathdisclure.pl
  tags: config,exposure,fpd,vbulletin

http:
  - method: GET
    path:
      - "{{BaseURL}}/forumdisplay.php?do[]=[test.dll]"
      - "{{BaseURL}}/calendar.php?do[]=[test.dll]"
      - "{{BaseURL}}/search.php?do[]=[test.dll]"
      - "{{BaseURL}}/forumrunner/include/album.php"
      - "{{BaseURL}}/core/vb5/route/channel.php"
      - "{{BaseURL}}/core/vb5/route/conversation.php"
      - "{{BaseURL}}/includes/api/interface/noncollapsed.php"
      - "{{BaseURL}}/includes/api/interface/collapsed.php"
      - "{{BaseURL}}/vbseo_sitemap/addons/vbseo_sm_vba.php"
      - "{{BaseURL}}/vbseo_sitemap/addons/vbseo_sm_vba_links.php"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Cannot modify header information"
          - "trim()"
          - "class_core.php"
          - "header already sent"
          - "Fatal error"		  
        condition: or

      - type: status
        status:
          - 200