id: ventrilo-config

info:
  name: Ventrilo Configuration File - Detect
  author: geeknik
  severity: high
  description: |
    Ventrilo configuration file was detected, The file discloses the application's Adminpassword and Password.
  reference:
    - https://www.ventrilo.com/setup.php
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
  tags: ventrilo,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/ventrilo_srv.ini"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[Server]"
          - "Name"
          - "Phonetic"
        condition: and

      - type: word
        part: header
        words:
          - "text/plain"

      - type: status
        status:
          - 200
# digest: 490a0046304402205d800b4bc88ceac5644fdb650babd3c88f11b230dd05a91dd4e55210748700e002207d711ec7105ba7765aee3f751f182d082c000a8e74dff2a49081834bfe32f09c:922c64590222798bb761d5b6d8e72950