id: web-config

info:
  name: Web Configuration File - Detect
  author: Yash Anand @yashanand155,DhiyaneshDK
  severity: info
  description: Web configuration file was detected.
  reference:
    - https://github.com/imhunterand/ApachSAL/blob/main/assets/exploits.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure

http:
  - method: GET
    path:
      - '{{BaseURL}}/web.config'
      - '{{BaseURL}}/../../web.config'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - <configuration>
          - <system.webServer>
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100c09359027a502d44632b75a7d31dd109df3f54ee92faa6503d0e04813e7d35ee022100d496d8e1a52a85b380d4bc5060ce51cac4860292b664727bdf20b1cb2c398b2e:922c64590222798bb761d5b6d8e72950