id: k8s-default-namespace-used

info:
  name: Default Namespace Usage in Deployments
  author: princechaddha
  severity: high
  description: Checks if Kubernetes Deployments are using the default namespace, which can lead to security risks and mismanagement issues.
  impact: |
    Using the default namespace for Kubernetes Deployments can increase security risks as it might allow broader access than necessary. It also complicates resource management across multiple teams and applications.
  remediation: |
    Avoid using the default namespace for Kubernetes Deployments. Create and specify dedicated namespaces tailored to specific applications or teams to enhance security and manage resources effectively.
  reference:
    - https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  tags: cloud,devops,kubernetes,k8s,devsecops,namespaces,k8s-cluster-security

flow: |
  code(1);
  for (let deployment of template.items) {
    set("deployment", deployment)
    javascript(1);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: kubectl get deployments --all-namespaces --output=json
    extractors:
      - type: json
        name: items
        internal: true
        json:
          - '.items[]'

javascript:
  - code: |
        deployment = JSON.parse(template.deployment);
        if (deployment.metadata.namespace.toLowerCase() === "default") {
          let result = (`Deployment '${deployment.metadata.name}' is using the default namespace, which is not recommended.`);
          Export(result);
        }

    extractors:
      - type: dsl
        dsl:
          - response
# digest: 490a0046304402207f8ca85f7b6453489655e4d84d1110f5a0449b4ca8a51a3655c6ad01c0a3120502205ca91771466cd711563a65ac9a1e55db43ab7430c0478f81b10b350b7f020985:922c64590222798bb761d5b6d8e72950