id: k8s-privileged-containers

info:
  name: Privileged Containers Found in Deployments
  author: princechaddha
  severity: critical
  description: Checks for containers running in privileged mode within Kubernetes Deployments, and now also checks for user privileges and privilege escalation settings.
  impact: |
    Running containers in privileged mode, as the root user, or with privilege escalation enabled can grant them access to host resources and could lead to security breaches if the container is compromised.
  remediation: |
    Ensure that no container in Kubernetes Deployments runs in privileged mode, as the root user, or with privilege escalation enabled. Modify the security context for each container to set `privileged: false`, `runAsUser` appropriately, and `allowPrivilegeEscalation: false`.
  reference:
    - https://kubernetes.io/docs/concepts/policy/pod-security-policy/#privileged
  tags: cloud,devops,kubernetes,k8s,devsecops,deployments,k8s-cluster-security

flow: |
  code(1);
  for (let deployment of template.items) {
    set("deployment", deployment)
    javascript(1);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: kubectl get deployments --all-namespaces --output=json
    extractors:
      - type: json
        name: items
        internal: true
        json:
          - '.items[]'

javascript:
  - code: |
        deployment = JSON.parse(template.deployment);
        for (let container of deployment.spec.template.spec.containers) {
          let sc = container.securityContext || {};
          if (sc.privileged || sc.runAsUser < 1000 || sc.allowPrivilegeEscalation) {
            let result = (`Deployment '${deployment.metadata.name}' in namespace '${deployment.metadata.namespace}' is running container '${container.name}' with insecure settings: Privileged=${sc.privileged}, runAsUser=${sc.runAsUser}, allowPrivilegeEscalation=${sc.allowPrivilegeEscalation}.`);
            Export(result);
            break;
          }
        }

    extractors:
      - type: dsl
        dsl:
          - response
# digest: 490a0046304402204696417ac223b6955bb46f04c93d9852537852df0b71ddb5363b1560d4ee2272022002d2203bdf1a048398e738fd2fddf19a1b078d1d5c126386e27cf98e48ac848f:922c64590222798bb761d5b6d8e72950