id: ispconfig-login

info:
  name: ISPConfig login
  author: non-things
  severity: info
  description: |
    ISPConfig Login template for authenticated ISPConfig testing.
  reference:
    - https://nuclei.projectdiscovery.io/templating-guide/workflows/
  tags: ispconfig,login

http:
  - raw:
     - |
       POST /login/index.php HTTP/1.1
       Host: {{Hostname}}
       Content-Type: application/x-www-form-urlencoded

       username={{username}}&password={{password}}&s_mod=login

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: header
        words:
          - 'Set-Cookie'

    extractors:
      - type: regex
        name: ispcsess-cookie
        part: header
        internal: true
        regex:
          - "Set-Cookie: (.*); path=/;"
