id: appsettings-file-disclosure

info:
  name: Application Setting file disclosure
  author: DhiyaneshDK,tess
  severity: high
  description: |
    appsetting.json file discloses the DB connection strings containing sensitive information.
  reference:
    - https://twitter.com/hacker_/status/1518003548855930882?s=20&t=BVauK0yUjVl5yL7rwy0Eag
  metadata:
    verified: true
    max-request: 2
  tags: exposure,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/appsettings.json"
      - "{{BaseURL}}/appsettings.Production.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ConnectionStrings"

      - type: word
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200
# digest: 4a0a0047304502200f0365d98c756de950d7c8b5fcf84a5e216c2f32845ea49dd33a742c01373e43022100ff7f119331f4dd48d9a870785a3c874350ea9c8d563baca7a5454639c71e61f5:922c64590222798bb761d5b6d8e72950