id: azure-pipelines-exposed

info:
  name: Azure Pipelines Configuration File Disclosure
  author: DhiyaneshDk
  severity: medium
  description: Azure Pipelines internal critical file is disclosed.
  classification:
    cpe: cpe:2.3:a:microsoft:azure_pipelines_agent:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    vendor: microsoft
    product: azure_pipelines_agent
    shodan-query: html:"azure-pipelines.yml"
  tags: config,exposure,azure,microsoft,cloud,devops,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.azure-pipelines.yml"
      - "{{BaseURL}}/azure-pipelines.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "trigger:"
          - "pool:"
          - "variables:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100f39d0e3a0451d55cf6f11f232ebd73bd6aa1d04a5bde12b03509edd28e8d95220220408eb15c089caf68b89feee83d3c431a7695aa73c978e28101c84b6c8e08ff79:922c64590222798bb761d5b6d8e72950