id: bitbucket-pipelines

info:
  name: BitBucket Pipelines Configuration Exposure
  author: DhiyaneshDK
  severity: info
  classification:
    cpe: cpe:2.3:a:atlassian:bitbucket:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: atlassian
    product: bitbucket
    shodan-query: html:"bitbucket-pipelines.yml"
  tags: exposure,bitbucket,devops,cicd,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/bitbucket-pipelines.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'pipelines:'
          - 'step:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a0048304602210094a2a849d07b5c3f3421bb9465889e7b24eae72031acad4a9b9be479ea1e96a6022100c76aee70e7d3f0e865c1cc2a79d0b31a0e6a42b775af8e2eec4f37f39e82bd7f:922c64590222798bb761d5b6d8e72950