id: composer-auth-json

info:
  name: Composer-auth Json File Disclosure
  author: DhiyaneshDK
  severity: low
  description: Composer Auth Josn file is disclosed.
  reference: https://www.exploit-db.com/ghdb/5768
  classification:
    cpe: cpe:2.3:a:getcomposer:composer:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    vendor: getcomposer
    product: composer
    google-query: intext:"index of /" ".composer-auth.json"
  tags: exposure,devops,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.composer-auth.json"
      - "{{BaseURL}}/vendor/webmozart/assert/.composer-auth.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'github-oauth'
          - 'github.com'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100b9537c198d28ab4e40039b949893a2592fb31dc8517a5b74bbf1e8186f2751ba022100bd3cad1875e675beee1d8ec4bb032464da6bcd4e0c491cd6f2f91137f524be08:922c64590222798bb761d5b6d8e72950