id: github-page-config

info:
  name: Github pages config file
  author: hahwul
  severity: info
  description: Find github pages config file.
  metadata:
    max-request: 1
  tags: github,exposure,config,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/_config.yml"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "jekyll"
          - "title"
          - "baseurl"
        condition: and
# digest: 4a0a00473045022100d68a85f6c22c05b08053d7e7813e2fd3ae3d7c997ff72c4a5fbcfffa768edbae02204c3b83882b6371e49702234e4e873bad1a3eb6563cdf25652432b737c8628bd2:922c64590222798bb761d5b6d8e72950