id: redmine-config

info:
  name: Redmine Configuration File - Detect
  author: DhiyaneshDK
  severity: high
  description: Redmine configuration file was detected.
  reference:
    - https://www.exploit-db.com/ghdb/5803
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
    cpe: cpe:2.3:a:redmine:redmine:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" configuration.yml
    product: redmine
    vendor: redmine
  tags: exposure,redmine,devops,edb,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/configuration.yml"
      - "{{BaseURL}}/config/configuration.yml"
      - "{{BaseURL}}/redmine/config/configuration.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "user_name"
          - "password"
          - "Redmine"
        condition: and

      - type: word
        part: header
        words:
          - "application/json"
          - "text/html"
        negative: true
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022048308633c37e8f2b750c31631a6f2333bd50d247a6e61221a82df6f7de89155b0221009e3423838f64628f66361aa9502da533ee6650a5d0b16be769c4109261907f97:922c64590222798bb761d5b6d8e72950