id: symfony-security

info:
  name: Symfony security.yml File Disclosure
  author: DhiyaneshDK
  severity: info
  classification:
    cpe: cpe:2.3:a:sensiolabs:symfony:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 3
    vendor: sensiolabs
    product: symfony
    google-query: intitle:"index of" "security.yml"
  tags: symfony,devops,exposure,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/security.yml"
      - "{{BaseURL}}/config/security.yml"
      - "{{BaseURL}}/app/config/security.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'security:'
          - 'providers:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450220596edeef430f30bba7f2c2fc04f9e3dca093ca18bcf3fe4de44833e817b3dafd022100a1b3db5e808a40f2283b6316b4ebd0d0860e72fc29d83f23802a8f14b2dfc75c:922c64590222798bb761d5b6d8e72950