id: azure-apim-resource-logs-not-configured
info:
  name: Azure API Management Service Resource Logs Not Configured
  author: princechaddha
  severity: medium
  description: |
    Ensure that your Azure API Management API services are configured to use resource logs to collect valuable information on API Management operations and errors. By enabling resource logs through a diagnostic setting, you can gather extensive information on the API requests received and handled by the Azure API Management service gateway.
  impact: |
    Failing to configure resource logs for Azure API Management services could result in a lack of visibility into API performance and errors, hindering effective management and troubleshooting.
  remediation: |
    Ensure that resource logs are enabled by setting up diagnostic settings for each Azure API Management service instance. This should include capturing all logs related to API operations and errors.
  reference:
    - https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-use-diagnostic-logs
  tags: cloud,devops,azure,microsoft,api-management,azure-cloud-config

flow: |
  code(1);
  for (let Resource of iterate(template.resourceList)) {
    Resource = JSON.parse(Resource);
    set("resource", Resource.name);
    set("resourceGroup", Resource.resourceGroup);
    code(2);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      az apim list --output json --query '[*].{name:name, resourceGroup:resourceGroup}'

    extractors:
      - type: json
        name: resourceList
        internal: true
        json:
          - '.[]'

  - engine:
      - sh
      - bash
    source: |
      az monitor diagnostic-settings list --resource $resource --resource-group $resourceGroup --resource-type "Microsoft.ApiManagement/service" --query '[*].name'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[]"

    extractors:
      - type: dsl
        dsl:
          - 'resource + " in " + resourceGroup + " does not have resource logs configured for Azure API Management services"'
# digest: 4b0a00483046022100fa72b8c6e12e6676aedb7103b528457c3b35a982bc76134b397aac5f10d1a5ad022100fab330a4b7342cbe5377d971fe079010a1531a5266d3c690b1e5855c660767d8:366f2a24c8eb519f6968bd8801c08ebe