id: azure-apim-system-assigned-identity-unconfigured
info:
  name: Azure API Management Service System-Assigned Managed Identity Not Configured
  author: princechaddha
  severity: medium
  description: |
    Ensure that your Azure API Management service instances are using system-assigned managed identities in order to allow secure access to other Microsoft Azure protected resources such as Azure Key Vaults. Using system-assigned managed identities minimizes risks, simplifies management, and maintains compliance with evolving cloud services.
  impact: |
    If system-assigned managed identities are not enabled for Azure API Management service instances, it may lead to insecure access management and complicates credentials management, increasing the risk of security breaches.
  remediation: |
    Enable system-assigned managed identities for your Azure API Management service instances through the Azure portal or by configuring the ARM template of your instance to include a system-assigned identity.
  reference:
    - https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-use-managed-service-identity
  tags: cloud,devops,azure,microsoft,api-management,azure-cloud-config

flow: |
  code(1);
  for (let ApiService of iterate(template.apiServiceList)) {
    ApiService = JSON.parse(ApiService);
    set("name", ApiService.name);
    set("resourceGroup", ApiService.resourceGroup);
    code(2);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      az apim list --output json --query '[*].{name:name, resourceGroup:resourceGroup}'

    extractors:
      - type: json
        name: apiServiceList
        internal: true
        json:
          - '.[]'

  - engine:
      - sh
      - bash
    source: |
      az apim show --name "$name" --resource-group "$resourceGroup" --query 'identity.type'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "UserAssigned"
          - "none"

    extractors:
      - type: dsl
        dsl:
          - 'name + " in " + resourceGroup + " does not have a system-assigned managed identity enabled"'
# digest: 4b0a00483046022100f74dfd2d32a194eaaa4e9dd3c5bde69edf9e9c85d9d9ccc4e950f265c9bc4b64022100d15c215e79b2da04d617998d335573befe15c61c6092120cdf1e635665cdc330:366f2a24c8eb519f6968bd8801c08ebe