id: grafana-default-login

info:
  name: Grafana Default Login
  author: pdteam
  severity: high
  description: Grafana default admin login credentials were detected.
  reference:
    - https://grafana.com/docs/grafana/latest/administration/configuration/#disable_brute_force_login_protection
    - https://stackoverflow.com/questions/54039604/what-is-the-default-username-and-password-for-grafana-login-page
    - https://github.com/grafana/grafana/issues/14755
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:L
    cvss-score: 8.3
    cwe-id: CWE-522
    cpe: cpe:2.3:a:grafana:grafana:*:*:*:*:*:*:*:*
  metadata:
    max-request: 2
    shodan-query: title:"Grafana"
    product: grafana
    vendor: grafana
  tags: grafana,default-login

http:
  - raw:
      - |
        POST /login HTTP/1.1
        Host: {{Hostname}}
        Accept: application/json, text/plain, */*
        Accept-Language: en-US,en;q=0.5
        Referer: {{BaseURL}}
        content-type: application/json

        {"user":"{{username}}","password":"{{password}}"}

    attack: pitchfork
    payloads:
      username:
        - admin
        - admin
      password:
        - prom-operator
        - admin

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "grafana_session" # Login cookie
        part: header

      - type: word
        part: body
        words:
          - "Logged in" # Logged in keyword

      - type: status
        status:
          - 200
# digest: 490a0046304402207e49fb8eefa2f428d26f8facb648650f7fcdc9f815c58866a4a44c77afaee08e02207f8186c6790812a164ac7857c7c15850bba6c77b96eb0b0be174ead561bb2045:922c64590222798bb761d5b6d8e72950