id: netlify-cms

info:
  name: Netlify CMS Admin Login Panel - Detect
  author: sullo
  severity: info
  description: Netlify CMS admin login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: panel,netlify

http:
  - method: GET
    path:
      - "{{BaseURL}}/admin/index.html"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "Netlify CMS"
        part: body
# digest: 490a0046304402207067874ab8e5631babfa20125ec3b72f8ae6bc5ca1bf453893d363e96e081eb0022067e610ba76e9b3df3af91fb291ed27abb98c7e636f64c9c373e70cbcda40dd0e:922c64590222798bb761d5b6d8e72950