id: oracle-application-server-panel

info:
  name: Oracle Application Server Login Panel - Detect
  author: righettod
  severity: info
  description: Oracle Application Server login panel was detected.
  metadata:
    shodan-query: http.title:"Oracle Containers for J2EE"
    max-request: 1
  tags: panel,oracle,containers,login,detect

http:
  - method: GET
    path:
      - "{{BaseURL}}/em/console/ias/oc4j/home"

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_any(to_lower(body), "login to oracle application server control", "oracle enterprise manager")'
        condition: and

    extractors:
      - type: regex
        group: 1
        regex:
          - '(?i)Copyright\s+&copy;\s+([0-9,\s]+),\s+Oracle'
