id: k8s-ns-usage-check

info:
  name: Ensure namespaces are utilized
  author: princechaddha
  severity: info
  description: Checks if Kubernetes namespaces are actively used to separate resources, which is critical for resource organization and access control.
  impact: |
    Lack of namespaces usage can lead to disorganized resources and potentially flawed access controls, impacting security and management.
  remediation: |
    Implement and use namespaces to organize resources within the Kubernetes cluster effectively. Define access controls and resource quotas on a per-namespace basis.
  reference:
    - https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  tags: cloud,devops,kubernetes,devsecops,namespaces,k8s,k8s-cluster-security

variables:
  argument: "namespaces"

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      kubectl get namespaces --output=json

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"items":'

      - type: word
        words:
          - '"Namespace"'
        negative: true

    extractors:
      - type: dsl
        dsl:
          - '"Kubernetes cluster is not utilizing " + argument'
# digest: 490a0046304402202672a3c25ca835a804437f2745bf15f10a66112c320e7a5b51dfe586de57195d0220710bfe5832faacbd8efd9f24794ba191e008f325933688c53fc3a982a784da90:366f2a24c8eb519f6968bd8801c08ebe