id: k8s-ns-usage-check

info:
  name: Ensure namespaces are utilized
  author: princechaddha
  severity: info
  description: Checks if Kubernetes namespaces are actively used to separate resources, which is critical for resource organization and access control.
  impact: |
    Lack of namespaces usage can lead to disorganized resources and potentially flawed access controls, impacting security and management.
  remediation: |
    Implement and use namespaces to organize resources within the Kubernetes cluster effectively. Define access controls and resource quotas on a per-namespace basis.
  reference:
    - https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  tags: cloud,devops,kubernetes,security,devsecops,namespaces

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      kubectl get namespaces --output=json

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"items":'

      - type: word
        words:
          - '"Namespace"'
        negative: true

    extractors:
      - type: dsl
        dsl:
          - "Kubernetes cluster is not utilizing namespaces."

# digest: 4b0a00483046022100a4752be32718d5e3bf67d19c2
