id: php-composer-binary

info:
  name: PHP Composer Binary - Exposure
  author: mayank_pandey01
  severity: info
  description: |
    This Nuclei template checks if the specified endpoints have publically accessible PHP Composer Binary.
  remediation: |
    Restrict access to the PHP Composer binary by implementing proper access controls and permissions.
  metadata:
    verified: true
    max-request: 1
  tags: php,composer,exposure,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/composer"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "/usr/bin/env php"
          - "<?php"
        condition: and

      - type: status
        status:
          - 200
# digest: 490a004630440220525d3c4b45ec5ede40ea39327037462a9ba4521dc0f877383f9fb693f50f1a3002206805b628226177d02bf4491701036c8178c1536c66ca3ca212916f24c95d2469:922c64590222798bb761d5b6d8e72950