id: php-composer-binary

info:
  name: Publically Accessible PHP Composer Binary
  author: mayank_pandey01
  severity: info
  description: |
    This Nuclei template checks if the specified endpoints have Publically Accessible PHP Composer Binary.
  remediation: |
    Restrict access to the PHP Composer binary by implementing proper access controls and permissions.
  metadata:
    verified: true
    shodan-query: title:"контроллер"
  tags: php,composer,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/composer"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "/usr/bin/env php"

      - type: status
        status:
          - 200
