id: kubelet-stats

info:
  name: Kubelet Stats
  author: sharath
  severity: info
  description: Scans for kubelet stats
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kubelet

http:
  - method: GET
    path:
      - "{{BaseURL}}/stats/summary"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"node":'
          - '"nodeName":'
        condition: and
# digest: 4b0a00483046022100969a45595296b9108b615b18b25f92c59431f21aee41365353eb457f9b8a379d022100dfd4170c6e290883244014ad5960b3631bd12a0d131187f08a78f262d9426397:922c64590222798bb761d5b6d8e72950