id: kubelet-metrics

info:
  name: Kubelet Metrics
  author: sharath,righettod
  severity: info
  description: |
    Kube Metrics Server was detected.
  reference:
    - https://github.com/kubernetes-sigs/metrics-server
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"Kube Metrics Server"
  tags: tech,k8s,kubernetes,devops,kubelet

http:
  - method: GET
    path:
      - "{{BaseURL}}/"
      - "{{BaseURL}}/metrics"

    stop-at-first-match: true
    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_any(to_lower(body), "<title>kube metrics server</title>", "kube_configmap_", "kube_pod_", "kube_secret_", "kube_deployment_", "kube_namespace_", "kube_service_")'
        condition: and
# digest: 490a0046304402207cc77daff1df23766326ac42748343ca85578d7931d3b2d4575807fbea3f2202022035fad2f258d2646e38fef87892a6d33e306ea69960ded58a6de951f9eb2b5a93:922c64590222798bb761d5b6d8e72950