id: device-guard-not-configured

info:
  name: Device Guard Not Configured
  author: princechaddha
  severity: high
  description: Verifies if Device Guard is not configured, reducing protection against unauthorized code execution.
  impact: |
    Not configuring Device Guard reduces the system's ability to block unauthorized code execution.
  remediation: |
    Configure Device Guard to enhance system protection.
  tags: device-guard,code,windows-audit

self-contained: true

code:
  - pre-condition: |
      IsWindows();
    engine:
      - powershell
      - powershell.exe
    args:
      - -ExecutionPolicy
      - Bypass
    pattern: "*.ps1"
    source: |
      Get-CimInstance -ClassName Win32_DeviceGuard -Namespace root\Microsoft\Windows\DeviceGuard

    matchers:
      - type: regex
        regex:
          - 'SecurityServicesConfigured\s+:\s+\{0\}'
          - 'SecurityServicesRunning\s+:\s+\{0\}'
          - 'VirtualizationBasedSecurityStatus\s+:\s+0'
        condition: or
# digest: 4a0a00473045022100c12f1b97700ad378f5b171e627b318d4e12efff99932fc85fe62d3775ba937d5022066e270cef44c88a71e3fad104e66af756d764d86873a90eb927fdcc9c0668426:922c64590222798bb761d5b6d8e72950