id: windows-system-restore-not-configured

info:
  name: System Restore Not Configured
  author: princechaddha
  severity: medium
  description: Checks if System Restore is not configured, which can prevent recovery from system issues.
  impact: |
    Without System Restore, recovering from system failures may require more drastic measures like reinstallation.
  remediation: |
    Configure System Restore to ensure you can roll back changes if needed.
  tags: windows,code,windows-audit

self-contained: true

code:
  - pre-condition: |
      IsWindows();
    engine:
      - powershell
      - powershell.exe
    args:
      - -ExecutionPolicy
      - Bypass
    pattern: "*.ps1"
    source: |
      $restorePoints = Get-ComputerRestorePoint -ErrorAction SilentlyContinue; if ($null -eq $restorePoints) { Write-Output "SystemRestoreUnavailable" }

    matchers:
      - type: word
        words:
          - "SystemRestoreUnavailable"

# digest: 4a0a004730450221009b090dbcbbb7287012a78e036f3f5e680c71ccdeab8e6f4ba4787cba64e2f6fa022058977d0afe7f6b8ccb30da3c3e6a27b3050f144e897902b25a7adfa730dda567:922c64590222798bb761d5b6d8e72950