id: k8s-def-egress-rules

info:
  name: Ensure egress rules are defined
  author: princechaddha
  severity: medium
  description: Checks for network policies that define specific egress rules, ensuring controlled outbound traffic.
  impact: |
    Lack of egress rules in network policies may allow unrestricted outbound network traffic. This can lead to potential security risks, including data exfiltration.
  remediation: |
    Define egress rules in the network policy to manage and restrict outbound traffic effectively. Specify allowed destinations and ports to limit network traffic.
  reference:
    - https://kubernetes.io/docs/concepts/services-networking/network-policies/
  tags: cloud,devops,kubernetes,security,devsecops,network

flow: |
  code(1);
  for (let policy of template.items) {
    set("policy", policy)
    javascript(1);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: kubectl get networkpolicies --all-namespaces --output=json
    extractors:
      - type: json
        name: items
        internal: true
        json:
          - '.items[] | {name: .metadata.name, namespace: .metadata.namespace, egress: .spec.egress}'

javascript:
  - code: |
       let policyData = template.policy;
       if (!policyData.egress || policyData.egress.length === 0) {
         let result = `Network policy '${policyData.name}' in namespace '${policyData.namespace}' does not define any egress rules.`;
         Export(result);
       }

    extractors:
      - type: dsl
        dsl:
          - response
# digest: 490a0046304402203da66eea889668b34e537e161930c32db95c287c91bf4b25ea42fab9207aa20b022066509c25e5056f4f842cc9720a481689aaf3c3208c6f91ce5dd051819e0325a6:366f2a24c8eb519f6968bd8801c08ebe