id: k8s-network-ingress-rules

info:
  name: Network policies define ingress
  author: princechaddha
  severity: medium
  description: Ensures network policies define ingress rules to control traffic flow within the cluster, enhancing security.
  impact: |
    Without defined ingress rules, network policies might allow unrestricted inbound traffic, potentially exposing the cluster to security threats. Properly defined ingress rules help mitigate this risk by restricting traffic flow.
  remediation: Define ingress rules in network policies to restrict and control inbound traffic within the Kubernetes cluster.
  reference:
    - https://kubernetes.io/docs/concepts/services-networking/network-policies/
  tags: cloud,devops,kubernetes,security,devsecops,networking

flow: |
  code(1);
  for (let networkPolicy of template.items) {
    set("networkPolicy", networkPolicy)
    javascript(1);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: kubectl get networkpolicies --all-namespaces --output=json
    extractors:
      - type: json
        name: items
        internal: true
        json:
          - '.items[]'

javascript:
  - code: |
        let networkPolicy = JSON.parse(template.networkPolicy);
        if (!networkPolicy.spec.ingress || networkPolicy.spec.ingress.length === 0) {
          let result = (`Network policy '${networkPolicy.metadata.name}' in namespace '${networkPolicy.metadata.namespace}' does not define any ingress rules.`);
          Export(result);
        }

    extractors:
      - type: dsl
        dsl:
          - response
# digest: 4a0a00473045022100c53e3615f3c1dd115d8efd4e9415177289e366c07ee24d4694d19c882c77044102203ce3bd2c002e4ab82073e7c770d39298407a1c40246b5c657104d01b4f642f6a:366f2a24c8eb519f6968bd8801c08ebe