id: k8s-ns-policy-set

info:
  name: Network policies specify namespace
  author: princechaddha
  severity: medium
  description: Checks for Kubernetes network policies that do not specify a namespace, potentially leading to misconfigurations and security risks.
  impact: |
    Failure to specify a namespace in network policies can cause the policies to not be enforced as expected, leading to potential security vulnerabilities where unauthorized traffic could be allowed.
  remediation: |
    Ensure that all network policies explicitly define the namespace they apply to. This helps in enforcing security boundaries and preventing cross-namespace traffic unless explicitly allowed.
  reference:
    - https://kubernetes.io/docs/concepts/services-networking/network-policies/
  tags: cloud,devops,kubernetes,security,devsecops,networking

flow: |
  code(1);
  for (let policy of template.items) {
    set("policy", policy)
    javascript(1);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: kubectl get networkpolicies --all-namespaces --output=json
    extractors:
      - type: json
        name: items
        internal: true
        json:
          - '.items[] | {policy: .metadata.name, namespace: .metadata.namespace}'

javascript:
  - code: |
        if (template.items.length === 0) {
          log(template.items.length)
          Export('No network policies found. Ensure that network policies are defined and namespaces are specified.');
        } else {
          template.items.forEach(policy => {
            let policyData = JSON.parse(policy);
            if (!policyData.namespace) {
              let result = (`Network Policy '${policyData.policy}' does not specify a namespace.`);
              Export(result);
            }
          });
        }

    extractors:
      - type: dsl
        dsl:
          - response
# digest: 4a0a0047304502204f78530d043f4ee9c2844ef6ea271cdee74ef99154f17f43f120ff4cad1ff417022100dc262780f80d0e64648e5fa555c35032837ae0ecd21c274df318d593c2a1a626:366f2a24c8eb519f6968bd8801c08ebe