id: k8s-netpol-egress-rules

info:
  name: Network policies define egress rules
  author: princechaddha
  severity: medium
  description: Checks for network policies in Kubernetes that do not define egress rules, which can leave the network exposed to external threats.
  impact: |
    Lack of egress rules in network policies can result in unrestricted outbound network traffic, which may allow data exfiltration or unauthorized access to external services.
  remediation: Define egress rules in all network policies to control outbound traffic from your Kubernetes pods, thereby reducing security risks.
  reference:
    - https://kubernetes.io/docs/concepts/services-networking/network-policies/
  tags: cloud,devops,kubernetes,security,devsecops,network

flow: |
  code(1);
  for (let policy of template.items) {
    set("policy", policy)
    javascript(1);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: kubectl get networkpolicies --all-namespaces --output=json
    extractors:
      - type: json
        name: items
        internal: true
        json:
          - '.items[] | {policy: .metadata.name, egress: .spec.egress}'

javascript:
  - code: |
        let policyData = JSON.parse(template.policy);
        if (!policyData.egress || policyData.egress.length === 0) {
          let result = (`Network policy '${policyData.policy}' does not define egress rules.`);
          Export(result);
        }

    extractors:
      - type: dsl
        dsl:
          - response
# digest: 4b0a00483046022100adb84e8a912b21d2e2bfd1f9253aec9cc33b6feb9fe7ee538ee0057e61ef8bb9022100d26ff6d9a2ac5f662df09dbb322793b0f9402594c96c361189367f58586344bc:366f2a24c8eb519f6968bd8801c08ebe