id: tcpconfig

info:
  name: TCP/IP Configuration Information - Detect
  author: dhiyaneshDK
  severity: low
  description:
  reference:
    - https://www.exploit-db.com/ghdb/6782
  tags: config,edb,logs

requests:
  - method: GET
    path:
      - "{{BaseURL}}/tcpconfig.html"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "TCP/IP Configuration"

      - type: status
        status:
          - 200

# Enhanced by md on 2023/03/15
