id: kube-api-pods

info:
  name: Kube API Pods
  author: sharath
  severity: info
  description: Scans for kube pods
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/namespaces/default/pods"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"PodList":'
          - '"items":'
        condition: and
# digest: 4b0a00483046022100b46cab844b433f8b6343a905c2ca771e1c898a8646d5faf52f0220dcd825d386022100e813f7c601f6d810781f0a97abe9e3b2d919b5ee936fcb3308746679e1221ae9:922c64590222798bb761d5b6d8e72950