id: kube-api-nodes

info:
  name: Kube API Nodes
  author: sharath,ritikchaddha
  severity: info
  description: Scans for kube nodes
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/nodes"

    matchers-condition: or
    matchers:
      - type: word
        part: body
        words:
          - '"NodeList":'
          - '"items":'
        condition: and

      - type: word
        part: body
        words:
          - '"containerRuntimeVersion"'
          - '"kubeletVersion": "v'
        condition: and
# digest: 4a0a004730450220520cd74849e9f49dfa16331b0a99d416fc9a0b4c5d7ce5d00d296353ff15418e022100c4ccd9fa72a4c6548a5554dbb4d7d284524aa396e87aa5f797876a47b8693abe:922c64590222798bb761d5b6d8e72950