id: kube-api-namespaces

info:
  name: Kube API Namespaces
  author: sharath
  severity: info
  description: Scans for kube namespaces
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/namespaces"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"NamespaceList":'
          - '"items":'
        condition: and
# digest: 490a004630440220416adfd30f16ce942c4649aef7c286c0089c13b0d1d93d4c2141a0a7ae537f9c02203cde4714edd6d5b42103a052cc73a1bc6e270fbf04895a5161d392a3ce8042fb:922c64590222798bb761d5b6d8e72950