id: kube-api-secrets

info:
  name: Kube API Secrets
  author: sharath
  severity: info
  description: Scans for kube secrets endpoint
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/namespaces/default/secrets"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"SecretList":'
          - '"items":'
        condition: and
# digest: 4a0a004730450220652e471edcee4ba687c8ff290b02c858f51e81994777cf76ce0d69a9ba9b80fc022100ec42c99f697b76145e82d44c4cbf8d011c635d08128f349873fb6cdd3b7963d8:922c64590222798bb761d5b6d8e72950