id: kube-api-version

info:
  name: Kube API Version
  author: sharath,raesene
  severity: info
  description: Searches for exposed Kubernetes API servers which return version information unauthenticated
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube

http:
  - method: GET
    path:
      - "{{BaseURL}}/version"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"major":'
          - '"minor":'
          - '"goVersion":'
        condition: and

    extractors:
      - type: json
        json:
          - ".gitVersion"
# digest: 490a0046304402205c3a1eb0cfada76d3834a74749179ceb17b24003a1db7a6882e363fd3c9fd8e70220286fb7f169f17feb87732de63c49a20c9457c4841cfbb5150e722b0b2df2fc12:922c64590222798bb761d5b6d8e72950