id: netlify-takeover

info:
  name: netlify takeover detection
  author: 0xPrial,pdteam
  severity: high
  description: netlify takeover was detected.
  reference:
    - https://github.com/EdOverflow/can-i-take-over-xyz/issues/40
    - https://monish-basaniwal.medium.com/how-i-found-my-first-subdomain-takeover-vulnerability-b7d5c17b61fd
    - https://github.com/EdOverflow/can-i-take-over-xyz/pull/289
  metadata:
    max-request: 1
  tags: takeover,netlify

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - Host != ip

      - type: word
        part: body
        words:
          - "Not Found - Request ID:"
        case-insensitive: true

      - type: word
        part: header
        words:
          - "Netlify"

    extractors:
      - type: dsl
        dsl:
          - cname
# digest: 4b0a00483046022100f2bd0e73a6fdd2336c0f2fc7325914a9b273c486f1811b48e981108790b8e227022100fa8a4fcb73f3f6f989eef4fdbef4ca0d13a6884d7b966972a4e460fb9bf91a81:922c64590222798bb761d5b6d8e72950