id: prometheus-exporter

info:
  name: Prometheus exporter detect
  author: jarijaas
  severity: info
  description: Prometheus exporter detector
  reference:
    - https://github.com/prometheus/prometheus/wiki/Default-port-allocations
  metadata:
    max-request: 1
  tags: prometheus,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Exporter'
          - '<a href="/metrics">Metrics</a>'
        condition: and

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "<title>(.*?)</title>"
# digest: 4b0a004830460221008db5477dd889743e7d41e9b9464a90d1f816d7936e2b0c903a60f9ea7300a6f3022100bfaa630f7676d722c2d14270981222574413aca8d612da4cd5904232a8aa5fdf:922c64590222798bb761d5b6d8e72950