id: prometheus-log

info:
  name: Exposed Prometheus
  author: dhiyaneshDK,thevillagehacker
  severity: low
  metadata:
    max-request: 2
  tags: prometheus,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/prometheus"
      - "{{BaseURL}}/actuator/prometheus"
      - "{{BaseURL}}/actuator/prometheus;%2f..%2f..%2f"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'gateway_request_total'
          - 'logback_events_total'
        condition: or

      - type: status
        status:
          - 200
