# Nuclei Configuration Profile for Misconfigurations Detection
#
# This configuration file is specifically tailored for detecting misconfigurations using Nuclei.
#
# Purpose:
# This profile is focused on identifying various misconfigurations that can lead to security vulnerabilities. Detecting and correcting misconfigurations is essential for maintaining the security and integrity of systems and applications.
#
# Included Templates:
# This configuration references specific templates designed to detect misconfigurations:
# - http/misconfiguration/: Templates for detecting misconfigurations in HTTP-based services.
# - network/misconfig/: Templates for detecting misconfigurations in network services.
# - javascript/misconfiguration/: Templates written using javascript protocol for detecting misconfigurations in applications.
#
# Running this profile
# You can run this profile using the following command:
# nuclei -profile misconfigurations -u https://example.com

templates:
  - http/misconfiguration/
  - network/misconfig/
  - javascript/misconfiguration/
