id: configure-aaa-service

info:
  name: Cisco AAA Service Configuration - Detect
  author: pussycat0x
  severity: info
  description: |
    Cisco authentication, authorization and accounting service configuration was detected.
  reference:
    - https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/security/a1/sec-a1-cr-book/sec-cr-a2.html#GUID-E05C2E00-C01E-4053-9D12-EC37C7E8EEC5
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  tags: file,audit,cisco,config-audit,cisco-switch,router

file:
  - extensions:
      - conf

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "aaa new-model"
        negative: true

      - type: word
        words:
          - "configure terminal"

# Enhanced by md on 2023/05/02
# digest: 490a00463044022010c6a53cdcb3bd01e656b657e4f4ed0b03f2ec8db50d452258d0326bb248500302204ebb975e99a15fd6a0a1c64f04537d44d2c4f6b9e81ab4226036556010b369de:922c64590222798bb761d5b6d8e72950