id: configure-service-timestamps-debug

info:
  name: Cisco Configure Service Timestamps for Debug - Detect
  author: pussycat0x
  severity: info
  description: |
    The configuration for service timestamps on Cisco devices was not implemented for debugging purposes. It's important to note that timestamps can be added to either debugging or logging messages independently.
  reference:
    - https://www.cisco.com/E-Learning/bulk/public/tac/cim/cib/using_cisco_ios_software/cmdrefs/service_timestamps.htm
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  tags: file,audit,cisco,config-audit,cisco-switch,router

file:
  - extensions:
      - conf

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "service timestamps debug datetime msec show-timezone localtime"
        negative: true

      - type: word
        words:
          - "configure terminal"

# Enhanced by md on 2023/05/02
# digest: 4b0a004830460221009c1717ec135ac15bfbf2e3c146358b111928151584962034d48ad49bcef8c93c022100c50c7c1b4d77f0a3d6595669806264af8c6ede8d7d8342d15e48f57f4c4ea942:922c64590222798bb761d5b6d8e72950