id: configure-service-timestamps-logmessages

info:
  name: Cisco Configure Service Timestamps Log Messages - Detect
  author: pussycat0x
  severity: info
  description: |
    Cisco service timestamp configuration for log messages was not implemented.
  reference:
    - https://www.cisco.com/E-Learning/bulk/public/tac/cim/cib/using_cisco_ios_software/cmdrefs/service_timestamps.htm
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  tags: file,audit,cisco,config-audit,cisco-switch,router

file:
  - extensions:
      - conf

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "service timestamps log datetime msec show-timezone localtime"
        negative: true

      - type: word
        words:
          - "configure terminal"

# Enhanced by md on 2023/05/02
# digest: 490a004630440220339621c290f654e02ef5e1c0afa242af8829e2e9e39e2ba37ad5d583bfbf364f0220035790b93ef6cba2f3c5cd50429d4d28b0eb9047e4ae9a2896e126d58f2d545e:922c64590222798bb761d5b6d8e72950