id: grafana-service-account-token

info:
  name: Grafana Service Account Token
  author: DhiyaneshDK
  severity: info
  reference:
    - https://github.com/returntocorp/semgrep-rules/blob/develop/generic/secrets/gitleaks/grafana-service-account-token.yaml
    - https://github.com/returntocorp/semgrep-rules/blob/develop/generic/secrets/gitleaks/grafana-service-account-token.go
  metadata:
    verified: true
  tags: grafana,file,keys
file:
  - extensions:
      - all

    extractors:
      - type: regex
        part: body
        regex:
          - (?i)\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:['|\"|\n|\r|\s|\x60|;]|$)
# digest: 4a0a004730450221008b832ce7e828503f3ae37d6b377ef43595b3ee2943d78d5447683557d535dadd02207393f686ddc61d00e018b5faedd2b7fe69c3668f9b3999f13ea45cc776c32fb1:922c64590222798bb761d5b6d8e72950