id: api-appveyor

info:
  name: AppVeyor API Test
  author: dwisiswant0
  severity: info
  reference:
    - https://www.appveyor.com/docs/api/
  metadata:
    max-request: 1
  tags: token-spray,appveyor

self-contained: true

http:
  - method: GET
    path:
      - "https://ci.appveyor.com/api/roles"

    headers:
      Content-Type: application/json
      Authorization: Bearer {{token}}
    matchers:
      - type: word
        part: body
        words:
          - '"roleId":'
          - '"created":'
        condition: and
# digest: 4b0a00483046022100dc37af68e53230423a2f2afd1e65f0d5110cb0359c6f468c6647a66e6283c916022100f5e0b3afb521c6492f24f9927b3721bb28198b4903ce80edcf61aa08d49dd7d7:922c64590222798bb761d5b6d8e72950