id: configure-dns-server

info:
  name: DNS Server Not Implemented - Detect
  author: pussycat0x
  severity: info
  description: |
    DNS is recommended to be configured over TLS. This prevents intermediate parties and potential attackers from viewing the content of DNS queries and can also assure that DNS is being provided by the expected DNS servers.
  reference: |
    https://docs.netgate.com/pfsense/en/latest/recipes/dns-over-tls.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
  tags: firewall,config,audit,pfsense,file

file:
  - extensions:
      - xml

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<dnsserver>"
        negative: true

      - type: word
        words:
          - "<pfsense>"
          - "<system>"
        condition: and

# Enhanced by md on 2023/05/04
# digest: 4b0a00483046022100fe4d9e9703d71a48774cfc32a2feea5075d911bf219e1ef65f89c719eacd884c022100dd9063d080a00cb9cc9de1e29627bc02c47a532c69c07e2e85d59e126a1aed2d:922c64590222798bb761d5b6d8e72950