id: docker-hub-pat

info:
  name: Docker Hub Personal Access Token
  author: DhiyaneshDK
  severity: info
  reference:
    - https://github.com/praetorian-inc/noseyparker/blob/main/crates/noseyparker/data/default/builtin/rules/dockerhub.yml
    - https://docs.docker.com/security/for-developers/access-tokens/
  metadata:
    verified: true
    max-request: 1
  tags: docker,exposure,tokens

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - \b(dckr_pat_[a-zA-Z0-9_-]{27})(?:$|[^a-zA-Z0-9_-])
# digest: 490a00463044022075b51f38debc046bfad4e7d80daefa7e238c1adcf03e2eedaa4155f1343eea6c0220121ec8102c04af71d65dc2cb55fbb43f06848d67c471d5ca52f000e0f1c8b1a3:922c64590222798bb761d5b6d8e72950