id: grafana-key

info:
  name: Grafana API Key
  author: DhiyaneshDK
  severity: info
  reference:
    - https://github.com/returntocorp/semgrep-rules/blob/develop/generic/secrets/gitleaks/grafana-api-key.yaml
    - https://github.com/returntocorp/semgrep-rules/blob/develop/generic/secrets/gitleaks/grafana-api-key.go
  metadata:
    verified: true
    max-request: 1
  tags: grafana,exposure,tokens

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - (?i)\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,2})(?:['|\"|\n|\r|\s|\x60|;]|$)
# digest: 4b0a004830460221009addf3fb940d9fadda93d000ebee4eedbb241fbb4c9760ef0ef76f03722a11e2022100b7bd6900e8788dbc7c7de7bc43eda22e608a64ad18a7bafafcffd893f5cb83f3:922c64590222798bb761d5b6d8e72950