id: grandstream-device-configuration

info:
  name: Grandstream Device Configuration
  author: dhiyaneshDK
  severity: info
  description: Exposed Grandstream device configuration page detected.
  classification:
    cpe: cpe:2.3:o:grandstream:ht801_firmware:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: grandstream
    product: ht801_firmware
    shodan-query: http.title:"Grandstream Device Configuration"
  tags: iot

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Grandstream Device Configuration</title>'

      - type: status
        status:
          - 200
# digest: 4b0a004830460221009f0b643070096460b97c7342ce51c6bd496377c1186b487ae7f2702c094f6960022100ea8030be280e0ec3d94126a58b92422f5b93013b23c2988ea59e8b618127a7fa:922c64590222798bb761d5b6d8e72950