id: settings-php-files

info:
  name: settings.php - Information Disclosure
  author: sheikhrishad
  severity: medium
  description: settings.php source code was detected via backup files.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 7
  tags: exposure,backup

http:
  - method: GET
    path:
      - "{{BaseURL}}/settings.php.bak"
      - "{{BaseURL}}/settings.php.dist"
      - "{{BaseURL}}/settings.php.old"
      - "{{BaseURL}}/settings.php.save"
      - "{{BaseURL}}/settings.php.swp"
      - "{{BaseURL}}/settings.php.txt"
      - "{{BaseURL}}/config/settings.old.php"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DB_NAME"
          - "DB"
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a004830460221009fd3e1f8712ed43969650f105ded371ff0de1a288ebf1a796f369ce2a1bf4325022100ad3cb349c3f6708fe1708a3be1de7fc332375fd3d1f9b9c5c51a3655626cffdd:922c64590222798bb761d5b6d8e72950