id: producthunt

info:
  name: Producthunt User Name Information - Detect
  author: dwisiswant0
  severity: info
  description: Producthunt user name information check was conducted.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: osint,osint-business,producthunt

self-contained: true

http:
  - method: GET
    path:
      - "https://www.producthunt.com/@{{user}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "s profile on Product Hunt"
# digest: 4a0a00473045022066a5e9fbaaa599a433f325f5e95fb5777c4dd4cdcde1452668baf51656411a0c022100de3b07aa42a17abd8be1e196d374758e0cee91ebb5f5318c7c2dc097d9c0e2ad:922c64590222798bb761d5b6d8e72950