id: azure-storage-private-endpoint-unconfigured
info:
  name: Azure Storage Private Endpoint Not Configured
  author: princechaddha
  severity: high
  description: |
    Ensure that private endpoints are configured for Microsoft Azure Storage accounts in order to allow clients and services to securely access data located over a network via an encrypted Private Link connection.
  impact: |
    Not using private endpoints for Azure Storage accounts can expose sensitive data to potential breaches by allowing data transmission over less secure networks.
  remediation: |
    Configure private endpoints for your Azure Storage accounts to ensure secure access via Private Link.
  reference:
    - https://docs.microsoft.com/en-us/azure/storage/common/storage-private-endpoints
  tags: cloud,devops,azure,microsoft,azure-storage,azure-cloud-config

flow: |
  code(1);
  for (let StorageAccount of iterate(template.storageAccounts)) {
    StorageAccount = JSON.parse(StorageAccount);
    set("name", StorageAccount.Name);
    code(2);
  }

self-contained: true
code:
  - engine:
      - sh
      - bash
    source: |
      az storage account list --query '[*].{"Name":name}'

    extractors:
      - type: json
        name: storageAccounts
        internal: true
        json:
          - '.[]'

  - engine:
      - sh
      - bash
    source: |
      az storage account show --name "$name" --query 'privateEndpointConnections' --output json

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '[]'

    extractors:
      - type: dsl
        dsl:
          - 'name + " does not have any configured private endpoints."'
# digest: 4a0a0047304502206a52edb1651c67b51d220db8414500ba1ae0c0e48f3eccf99cf57a5681bc1e77022100bb1af7ca2af738a606f03704089e39c48f09fc7aa321c8c7e5481845be446d46:366f2a24c8eb519f6968bd8801c08ebe