id: kubernetes-version

info:
  name: Kubernetes Version Exposure
  author: raesene,idealphase
  severity: info
  description: Searches for exposed Kubernetes API servers which return version information unauthenticated. For Google Kubernetes Engine (GKE) and Amazon Elastic Kubernetes Service (EKS) this template will extract default patch version for you.
  reference:
    - https://cloud.google.com/kubernetes-engine/docs/release-notes
    - https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
  metadata:
    max-request: 1
    shodan-query: product:"Kubernetes" version:"1.21.5-eks-bc4871b"
  tags: tech,k8s,kubernetes,devops

http:
  - method: GET
    path:
      - "{{BaseURL}}/version"

    matchers:
      - type: word
        words:
          - "gitVersion"
          - "goVersion"
          - "platform"
        condition: and

    extractors:
      - type: json
        json:
          - '.gitVersion'
# digest: 490a0046304402205f19555a48bfd59ebf8521ecb5c32466fe57e39d8b573c60fe0319f321acc4e802202d531ffb586c96643374f55dd1b23ecfed902fd04271649ef625a90e7366055f:922c64590222798bb761d5b6d8e72950