id: etcd-version

info:
  name: Etcd Version - Detect
  author: pussycat0x
  severity: info
  description: Template detects Etcd version.
  reference:
    - https://etcd.io/
  metadata:
    verified: true
    max-request: 1
    shodan-query: product:"etcd"
  tags: tech,k8s,kubernetes,devops,etcd

http:
  - method: GET
    path:
      - "{{BaseURL}}/version"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"etcdserver"'
          - '"etcdcluster"'
        condition: and

      - type: word
        part: header
        words:
          - "application/json"

      - type: status
        status:
          - 200

    extractors:
      - type: dsl
        dsl:
          - 'trim(body,"{}")'
# digest: 4a0a00473045022100bd9aa7989755207898d94c1e1e4849b86069c33a4fd8a8d2125c26c5aad8e7ca022074c969e21fdc5f942b62b68b99812ccb2eb7b7a5e87bc1a43be9322fb87b4aba:922c64590222798bb761d5b6d8e72950