id: springboot-autoconfig

info:
  name: Detect Springboot autoconfig Actuator
  author: pussycat0x
  severity: low
  description: Displays an auto-configuration report showing all auto-configuration candidates and the reason why they 'were' or 'were not' applied.
  metadata:
    max-request: 2
  tags: springboot,exposure,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/autoconfig"
      - "{{BaseURL}}/actuator/autoconfig"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "positiveMatches"
          - "AuditAutoConfiguration#auditListener"
          - "EndpointAutoConfiguration#beansEndpoint"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100c4ceeac4a3532af5d73cdd4ed634dbd623e93d8af46632fb21cecd3d8b9bd0150220791b1f89f3ef5f0b6553ac93c873d5e24f7533755c7400335c16df5d4c61426b:922c64590222798bb761d5b6d8e72950