id: aws-xray-application

info:
  name: AWS X-Ray Sample Application
  author: DhiyaneshDk
  severity: info
  description: AWS X-Ray is a service that helps developers analyze and debug distributed applications.
  reference:
    - https://www.facebook.com/ExWareLabs/photos/a.361854183878462/5566269380103557/
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"AWS X-Ray Sample Application"
  tags: misconfig,aws,x-ray,amazon

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<title>AWS X-Ray Sample Application</title>'

      - type: word
        part: header
        words:
          - text/html

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100fbbeb03a4b0c2ba4c6f85c1863d1e8c83bcf021aec97274884bde6fd9cf05c4e022100a3230d1f50acc376aec025adae3c9f476a42660cb0de03fd6fa72eb3da6caf97:922c64590222798bb761d5b6d8e72950