name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2018/CVE-2018-10942.yaml'
    - 'http/cves/2023/CVE-2023-27639.yaml'
    - 'http/cves/2023/CVE-2023-27640.yaml'
    - 'http/cves/2023/CVE-2023-48023.yaml'
    - 'http/cves/2023/CVE-2023-6875.yaml'
    - 'http/default-logins/node-red/nodered-default-login.yaml'
    - 'http/default-logins/powershell/powershell-default-login.yaml'
    - 'http/exposed-panels/autoset-detect.yaml'
    - 'http/exposed-panels/compalex-detect.yaml'
    - 'http/exposures/configs/vbulletin-path-disclosure.yaml'
    - 'http/vulnerabilities/juniper/junos-xss.yaml'
    - 'http/vulnerabilities/prestashop/prestashop-blocktestimonial-file-upload.yaml'
    - 'http/vulnerabilities/vbulletin/vbulletin-backdoor.yaml'
    - 'vulnerabilities/apache/apache-nifi-rce.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
