name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cnvd/2023/CNVD-2023-96945.yaml'
    - 'http/cves/2023/CVE-2023-42344.yaml'
    - 'http/cves/2023/CVE-2023-45671.yaml'
    - 'http/cves/2023/CVE-2023-48777.yaml'
    - 'http/cves/2024/CVE-2024-0713.yaml'
    - 'http/cves/2024/CVE-2024-1208.yaml'
    - 'http/cves/2024/CVE-2024-1209.yaml'
    - 'http/cves/2024/CVE-2024-1210.yaml'
    - 'http/cves/2024/CVE-2024-1709.yaml'
    - 'http/cves/2024/CVE-2024-25600.yaml'
    - 'http/exposed-panels/connectwise-panel.yaml'
    - 'http/exposed-panels/fortinet/fortiauthenticator-detect.yaml'
    - 'http/misconfiguration/installer/connectwise-setup.yaml'
    - 'http/vulnerabilities/dahua/dahua-bitmap-fileupload.yaml'
    - 'http/vulnerabilities/yonyou/yonyou-ufida-nc-lfi.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
