name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2023/CVE-2023-36347.yaml'
    - 'http/cves/2023/CVE-2023-43374.yaml'
    - 'http/cves/2024/CVE-2024-0200.yaml'
    - 'http/exposed-panels/craftercms-panel.yaml'
    - 'http/exposed-panels/nocodb-panel.yaml'
    - 'http/exposed-panels/qlikview-accesspoint-panel.yaml'
    - 'http/exposed-panels/unleash-panel.yaml'
    - 'http/misconfiguration/installer/moosocial-installer.yaml'
    - 'http/misconfiguration/installer/phpmyfaq-installer.yaml'
    - 'http/misconfiguration/unigui-server-monitor-exposure.yaml'
    - 'http/technologies/craftercms-detect.yaml'
    - 'http/technologies/statamic-detect.yaml'
    - 'http/technologies/tinyproxy-detect.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
