name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/vulnerabilities/nextjs/nextjs-middleware-cache.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
