name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cnvd/2024/CNVD-2024-15077.yaml'
    - 'http/cves/2022/CVE-2022-1580.yaml'
    - 'http/cves/2022/CVE-2022-34534.yaml'
    - 'http/cves/2023/CVE-2023-2059.yaml'
    - 'http/cves/2023/CVE-2023-3077.yaml'
    - 'http/cves/2023/CVE-2023-48084.yaml'
    - 'http/cves/2024/CVE-2024-21683.yaml'
    - 'http/cves/2024/CVE-2024-24919.yaml'
    - 'http/cves/2024/CVE-2024-3495.yaml'
    - 'http/cves/2024/CVE-2024-5230.yaml'
    - 'http/default-logins/ampjuke-default-login.yaml'
    - 'http/default-logins/cambium-networks/cambium-networks-default-login.yaml'
    - 'http/default-logins/digital-watchdog/digital-watchdog-default-login.yaml'
    - 'http/exposed-panels/busybox-repository-browser.yaml'
    - 'http/exposed-panels/cisco-firepower-panel.yaml'
    - 'http/exposed-panels/digital-watchdog-panel.yaml'
    - 'http/exposed-panels/fortinet/fortisiem-panel.yaml'
    - 'http/exposed-panels/vrealize-hyperic-login-panel.yaml'
    - 'http/exposures/tokens/wechat/wechat-secret-key.yaml'
    - 'http/iot/netgear-boarddataww-rce.yaml'
    - 'http/misconfiguration/cubebackup-setup-installer.yaml'
    - 'http/misconfiguration/installer/activecollab-installer.yaml'
    - 'http/misconfiguration/installer/cms-made-simple-installer.yaml'
    - 'http/misconfiguration/installer/ejbca-enterprise-installer.yaml'
    - 'http/misconfiguration/installer/flarum-installer.yaml'
    - 'http/misconfiguration/installer/fleetcart-installer.yaml'
    - 'http/misconfiguration/installer/glpi-installer.yaml'
    - 'http/misconfiguration/installer/invicti-enterprise-installer.yaml'
    - 'http/misconfiguration/installer/invoice-ninja-installer.yaml'
    - 'http/misconfiguration/installer/jfa-go-installer.yaml'
    - 'http/misconfiguration/installer/justfans-installer.yaml'
    - 'http/misconfiguration/installer/librenms-installer.yaml'
    - 'http/misconfiguration/installer/mura-cms-setup-installer.yaml'
    - 'http/misconfiguration/installer/onlyoffice-installer.yaml'
    - 'http/misconfiguration/installer/openemr-setup-installer.yaml'
    - 'http/misconfiguration/installer/pandora-fms-installer.yaml'
    - 'http/misconfiguration/installer/profittrailer-installer.yaml'
    - 'http/misconfiguration/installer/projectsend-installer.yaml'
    - 'http/misconfiguration/installer/snipe-it-installer.yaml'
    - 'http/misconfiguration/installer/stackposts-installer.yaml'
    - 'http/misconfiguration/installer/tastyigniter-installer.yaml'
    - 'http/misconfiguration/installer/ubersmith-installer.yaml'
    - 'http/misconfiguration/installer/uvdesk-helpdesk-installer.yaml'
    - 'http/misconfiguration/installer/virtual-smartzone-installer.yaml'
    - 'http/technologies/gotweb-detect.yaml'
    - 'http/vulnerabilities/other/array-vpn-lfi.yaml'
    - 'http/vulnerabilities/other/cerio-dt-rce.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
