name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2015/CVE-2015-2794.yaml'
    - 'http/cves/2023/CVE-2023-42343.yaml'
    - 'http/cves/2023/CVE-2023-46574.yaml'
    - 'http/exposures/docker-daemon-exposed.yaml'
    - 'http/token-spray/api-openai.yaml'
    - 'http/vulnerabilities/ruijie/ruijie-nmc-sync-rce.yaml'
    - 'http/vulnerabilities/ruijie/ruijie-rg-eg-web-mis-rce.yaml'
    - 'http/vulnerabilities/yonyou/yonyou-ksoa-dept-sqli.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
