name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'cloud/aws/sns/sns-public-subscribe-access.yaml'
    - 'dast/vulnerabilities/sqli/time-based-sqli.yaml'
    - 'http/cves/2021/CVE-2021-38146.yaml'
    - 'http/cves/2021/CVE-2021-38147.yaml'
    - 'http/cves/2021/CVE-2021-43831.yaml'
    - 'http/cves/2023/CVE-2023-32068.yaml'
    - 'http/cves/2023/CVE-2023-37645.yaml'
    - 'http/cves/2023/CVE-2023-38194.yaml'
    - 'http/cves/2023/CVE-2023-43472.yaml'
    - 'http/cves/2023/CVE-2023-45136.yaml'
    - 'http/cves/2023/CVE-2023-46732.yaml'
    - 'http/cves/2023/CVE-2023-48241.yaml'
    - 'http/cves/2023/CVE-2023-50719.yaml'
    - 'http/cves/2023/CVE-2023-50720.yaml'
    - 'http/cves/2023/CVE-2023-51449.yaml'
    - 'http/cves/2023/CVE-2023-6505.yaml'
    - 'http/cves/2023/CVE-2023-6786.yaml'
    - 'http/cves/2024/CVE-2024-0250.yaml'
    - 'http/cves/2024/CVE-2024-0939.yaml'
    - 'http/cves/2024/CVE-2024-1728.yaml'
    - 'http/cves/2024/CVE-2024-23692.yaml'
    - 'http/cves/2024/CVE-2024-24112.yaml'
    - 'http/cves/2024/CVE-2024-24565.yaml'
    - 'http/cves/2024/CVE-2024-2621.yaml'
    - 'http/cves/2024/CVE-2024-27718.yaml'
    - 'http/cves/2024/CVE-2024-28995.yaml'
    - 'http/cves/2024/CVE-2024-29824.yaml'
    - 'http/cves/2024/CVE-2024-29895.yaml'
    - 'http/cves/2024/CVE-2024-29973.yaml'
    - 'http/cves/2024/CVE-2024-31750.yaml'
    - 'http/cves/2024/CVE-2024-31982.yaml'
    - 'http/cves/2024/CVE-2024-32113.yaml'
    - 'http/cves/2024/CVE-2024-3274.yaml'
    - 'http/cves/2024/CVE-2024-34982.yaml'
    - 'http/cves/2024/CVE-2024-3552.yaml'
    - 'http/cves/2024/CVE-2024-36837.yaml'
    - 'http/cves/2024/CVE-2024-37393.yaml'
    - 'http/exposed-panels/lorex-panel.yaml'
    - 'http/exposed-panels/oracle-application-server-panel.yaml'
    - 'http/exposed-panels/turnkey-lamp-panel.yaml'
    - 'http/exposed-panels/veeam-backup-manager-login.yaml'
    - 'http/exposed-panels/wildix-collaboration-panel.yaml'
    - 'http/misconfiguration/apache/apache-server-status-localhost.yaml'
    - 'http/misconfiguration/cookies-without-secure.yaml'
    - 'http/technologies/nperf-server-detect.yaml'
    - 'http/technologies/wordpress/plugins/copy-delete-posts.yaml'
    - 'http/technologies/wordpress/plugins/image-optimization.yaml'
    - 'http/technologies/wordpress/plugins/royal-elementor-addons.yaml'
    - 'http/technologies/wordpress/plugins/simple-history.yaml'
    - 'http/technologies/wordpress/plugins/sticky-header-effects-for-elementor.yaml'
    - 'http/technologies/wordpress/plugins/woocommerce-legacy-rest-api.yaml'
    - 'http/vulnerabilities/gradio/gradio-lfi.yaml'
    - 'http/vulnerabilities/gradio/gradio-ssrf.yaml'
    - 'network/detection/mikrotik-ssh-detect.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    if: github.repository == 'projectdiscovery/nuclei-templates'
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
