name: Sync Repositories Workflow
on:
  push:
    paths:
    - '.new-additions'
    - 'http/cves/2024/CVE-2024-1208.yaml'
    - 'http/cves/2024/CVE-2024-1209.yaml'
    - 'http/cves/2024/CVE-2024-1210.yaml'
    - 'http/cves/2024/CVE-2024-25600.yaml'
    - 'http/exposed-panels/fortinet/fortiauthenticator-detect.yaml'
    - 'http/misconfiguration/installer/connectwise-setup.yaml'
    - 'http/misconfiguration/screenconnect-authentication-bypass.yaml'
  workflow_dispatch:
jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Remote Workflow with curl
      run: |
        curl -i -s -k -X 'POST' -H 'Host: api.github.com' -H "Authorization: token ${{ secrets.GTOKEN }}" --data-binary $'{\"ref\":\"main\"}' 'https://api.github.com/repos/projectdiscovery/early-templates/actions/workflows/reposync.yml/dispatches'
