id: bigip-config-utility

info:
  name: BIG-IP Configuration Utility detected
  author: dwisiswant0
  severity: info
  metadata:
    max-request: 3
  tags: tech,bigip

http:
  - method: GET
    path:
      - "{{BaseURL}}/tmui/login.jsp"
      - "{{BaseURL}}/tmui/tmui/login/welcome.jsp"

    matchers:
      - type: word
        words:
          - "Welcome to the BIG-IP"
          - "Configuration Utility"
        condition: and
        part: body

  - method: GET
    path:
      - "{{BaseURL}}/mgmt/tm/sys/management-ip"

    matchers:
      - type: word
        words:
          - "Www-Authenticate: Basic realm"
          - "Enterprise Manager"
        condition: and
        part: header

      - type: word
        words:
          - "check your user-id and password and try again"
        part: body
# digest: 490a00463044022067708eae9e6f5bc35e733a12a66312fca1474f8854f03c84fc56ca81ebb55ae6022028cdeb138a261ca8747e299f9a032c27ced3a0ee610543a6b6e3492576b474e5:922c64590222798bb761d5b6d8e72950